// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APIAiGovernanceV1ClassifierTemplateServiceInstantiateClassifierTemplateRequest struct {
	TemplateID                           string                                       `pathParam:"style=simple,explode=false,name=template_id"`
	InstantiateClassifierTemplateRequest *shared.InstantiateClassifierTemplateRequest `request:"mediaType=application/json"`
}

func (c *C1APIAiGovernanceV1ClassifierTemplateServiceInstantiateClassifierTemplateRequest) GetTemplateID() string {
	if c == nil {
		return ""
	}
	return c.TemplateID
}

func (c *C1APIAiGovernanceV1ClassifierTemplateServiceInstantiateClassifierTemplateRequest) GetInstantiateClassifierTemplateRequest() *shared.InstantiateClassifierTemplateRequest {
	if c == nil {
		return nil
	}
	return c.InstantiateClassifierTemplateRequest
}

// #region class-body-c1apiaigovernancev1classifiertemplateserviceinstantiateclassifiertemplaterequest
// #endregion class-body-c1apiaigovernancev1classifiertemplateserviceinstantiateclassifiertemplaterequest

type C1APIAiGovernanceV1ClassifierTemplateServiceInstantiateClassifierTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	InstantiateClassifierTemplateResponse *shared.InstantiateClassifierTemplateResponse
}

func (c *C1APIAiGovernanceV1ClassifierTemplateServiceInstantiateClassifierTemplateResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAiGovernanceV1ClassifierTemplateServiceInstantiateClassifierTemplateResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAiGovernanceV1ClassifierTemplateServiceInstantiateClassifierTemplateResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIAiGovernanceV1ClassifierTemplateServiceInstantiateClassifierTemplateResponse) GetInstantiateClassifierTemplateResponse() *shared.InstantiateClassifierTemplateResponse {
	if c == nil {
		return nil
	}
	return c.InstantiateClassifierTemplateResponse
}

// #region class-body-c1apiaigovernancev1classifiertemplateserviceinstantiateclassifiertemplateresponse
// #endregion class-body-c1apiaigovernancev1classifiertemplateserviceinstantiateclassifiertemplateresponse
