// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APISecretsV1PaperSecretAdminServiceGetRequest struct {
	VaultID string `pathParam:"style=simple,explode=false,name=vault_id"`
}

func (c *C1APISecretsV1PaperSecretAdminServiceGetRequest) GetVaultID() string {
	if c == nil {
		return ""
	}
	return c.VaultID
}

// #region class-body-c1apisecretsv1papersecretadminservicegetrequest
// #endregion class-body-c1apisecretsv1papersecretadminservicegetrequest

type C1APISecretsV1PaperSecretAdminServiceGetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	PaperSecretAdminServiceGetResponse *shared.PaperSecretAdminServiceGetResponse
}

func (c *C1APISecretsV1PaperSecretAdminServiceGetResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APISecretsV1PaperSecretAdminServiceGetResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APISecretsV1PaperSecretAdminServiceGetResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APISecretsV1PaperSecretAdminServiceGetResponse) GetPaperSecretAdminServiceGetResponse() *shared.PaperSecretAdminServiceGetResponse {
	if c == nil {
		return nil
	}
	return c.PaperSecretAdminServiceGetResponse
}

// #region class-body-c1apisecretsv1papersecretadminservicegetresponse
// #endregion class-body-c1apisecretsv1papersecretadminservicegetresponse
