// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteRequestableEntryRequest struct {
	CatalogID                                                    string                                                               `pathParam:"style=simple,explode=false,name=catalog_id"`
	AppID                                                        string                                                               `pathParam:"style=simple,explode=false,name=app_id"`
	EntitlementID                                                string                                                               `pathParam:"style=simple,explode=false,name=entitlement_id"`
	RequestCatalogManagementServiceDeleteRequestableEntryRequest *shared.RequestCatalogManagementServiceDeleteRequestableEntryRequest `request:"mediaType=application/json"`
}

func (c *C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteRequestableEntryRequest) GetCatalogID() string {
	if c == nil {
		return ""
	}
	return c.CatalogID
}

func (c *C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteRequestableEntryRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteRequestableEntryRequest) GetEntitlementID() string {
	if c == nil {
		return ""
	}
	return c.EntitlementID
}

func (c *C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteRequestableEntryRequest) GetRequestCatalogManagementServiceDeleteRequestableEntryRequest() *shared.RequestCatalogManagementServiceDeleteRequestableEntryRequest {
	if c == nil {
		return nil
	}
	return c.RequestCatalogManagementServiceDeleteRequestableEntryRequest
}

type C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteRequestableEntryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Empty response for delete operation
	RequestCatalogManagementServiceDeleteRequestableEntryResponse *shared.RequestCatalogManagementServiceDeleteRequestableEntryResponse
}

func (c *C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteRequestableEntryResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteRequestableEntryResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteRequestableEntryResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteRequestableEntryResponse) GetRequestCatalogManagementServiceDeleteRequestableEntryResponse() *shared.RequestCatalogManagementServiceDeleteRequestableEntryResponse {
	if c == nil {
		return nil
	}
	return c.RequestCatalogManagementServiceDeleteRequestableEntryResponse
}
