// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APIFunctionsV1FunctionsInvocationServiceGetResultDownloadURLRequest struct {
	FunctionID string `pathParam:"style=simple,explode=false,name=function_id"`
	ID         string `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APIFunctionsV1FunctionsInvocationServiceGetResultDownloadURLRequest) GetFunctionID() string {
	if c == nil {
		return ""
	}
	return c.FunctionID
}

func (c *C1APIFunctionsV1FunctionsInvocationServiceGetResultDownloadURLRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apifunctionsv1functionsinvocationservicegetresultdownloadurlrequest
// #endregion class-body-c1apifunctionsv1functionsinvocationservicegetresultdownloadurlrequest

type C1APIFunctionsV1FunctionsInvocationServiceGetResultDownloadURLResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	FunctionsInvocationServiceGetResultDownloadURLResponse *shared.FunctionsInvocationServiceGetResultDownloadURLResponse
}

func (c *C1APIFunctionsV1FunctionsInvocationServiceGetResultDownloadURLResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIFunctionsV1FunctionsInvocationServiceGetResultDownloadURLResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIFunctionsV1FunctionsInvocationServiceGetResultDownloadURLResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIFunctionsV1FunctionsInvocationServiceGetResultDownloadURLResponse) GetFunctionsInvocationServiceGetResultDownloadURLResponse() *shared.FunctionsInvocationServiceGetResultDownloadURLResponse {
	if c == nil {
		return nil
	}
	return c.FunctionsInvocationServiceGetResultDownloadURLResponse
}

// #region class-body-c1apifunctionsv1functionsinvocationservicegetresultdownloadurlresponse
// #endregion class-body-c1apifunctionsv1functionsinvocationservicegetresultdownloadurlresponse
