// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/v2/internal/sdk/models/shared"
	"net/http"
)

type C1APIFindingV1FindingRoutingRuleServiceListFindingRoutingRulesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	ListFindingRoutingRulesResponse *shared.ListFindingRoutingRulesResponse
}

func (c *C1APIFindingV1FindingRoutingRuleServiceListFindingRoutingRulesResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIFindingV1FindingRoutingRuleServiceListFindingRoutingRulesResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIFindingV1FindingRoutingRuleServiceListFindingRoutingRulesResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIFindingV1FindingRoutingRuleServiceListFindingRoutingRulesResponse) GetListFindingRoutingRulesResponse() *shared.ListFindingRoutingRulesResponse {
	if c == nil {
		return nil
	}
	return c.ListFindingRoutingRulesResponse
}

// #region class-body-c1apifindingv1findingroutingruleservicelistfindingroutingrulesresponse
// #endregion class-body-c1apifindingv1findingroutingruleservicelistfindingroutingrulesresponse
