// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APIAppV1ConnectorServiceListRequest struct {
	AppID     string  `pathParam:"style=simple,explode=false,name=app_id"`
	PageSize  *int    `queryParam:"style=form,explode=true,name=page_size"`
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
}

func (c *C1APIAppV1ConnectorServiceListRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIAppV1ConnectorServiceListRequest) GetPageSize() *int {
	if c == nil {
		return nil
	}
	return c.PageSize
}

func (c *C1APIAppV1ConnectorServiceListRequest) GetPageToken() *string {
	if c == nil {
		return nil
	}
	return c.PageToken
}

type C1APIAppV1ConnectorServiceListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The ConnectorServiceListResponse message contains a list of results and a nextPageToken if applicable
	ConnectorServiceListResponse *shared.ConnectorServiceListResponse
}

func (c *C1APIAppV1ConnectorServiceListResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAppV1ConnectorServiceListResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAppV1ConnectorServiceListResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIAppV1ConnectorServiceListResponse) GetConnectorServiceListResponse() *shared.ConnectorServiceListResponse {
	if c == nil {
		return nil
	}
	return c.ConnectorServiceListResponse
}
