// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APISessionPolicyV1SessionPolicyServiceGetRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (c *C1APISessionPolicyV1SessionPolicyServiceGetRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// #region class-body-c1apisessionpolicyv1sessionpolicyservicegetrequest
// #endregion class-body-c1apisessionpolicyv1sessionpolicyservicegetrequest

type C1APISessionPolicyV1SessionPolicyServiceGetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	SessionPolicyServiceGetResponse *shared.SessionPolicyServiceGetResponse
}

func (c *C1APISessionPolicyV1SessionPolicyServiceGetResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APISessionPolicyV1SessionPolicyServiceGetResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APISessionPolicyV1SessionPolicyServiceGetResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APISessionPolicyV1SessionPolicyServiceGetResponse) GetSessionPolicyServiceGetResponse() *shared.SessionPolicyServiceGetResponse {
	if c == nil {
		return nil
	}
	return c.SessionPolicyServiceGetResponse
}

// #region class-body-c1apisessionpolicyv1sessionpolicyservicegetresponse
// #endregion class-body-c1apisessionpolicyv1sessionpolicyservicegetresponse
