// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APIAppV1ConnectorServiceForceSyncRequest struct {
	AppID            string                   `pathParam:"style=simple,explode=false,name=app_id"`
	ConnectorID      string                   `pathParam:"style=simple,explode=false,name=connector_id"`
	ForceSyncRequest *shared.ForceSyncRequest `request:"mediaType=application/json"`
}

func (c *C1APIAppV1ConnectorServiceForceSyncRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIAppV1ConnectorServiceForceSyncRequest) GetConnectorID() string {
	if c == nil {
		return ""
	}
	return c.ConnectorID
}

func (c *C1APIAppV1ConnectorServiceForceSyncRequest) GetForceSyncRequest() *shared.ForceSyncRequest {
	if c == nil {
		return nil
	}
	return c.ForceSyncRequest
}

type C1APIAppV1ConnectorServiceForceSyncResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	ForceSyncResponse *shared.ForceSyncResponse
}

func (c *C1APIAppV1ConnectorServiceForceSyncResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAppV1ConnectorServiceForceSyncResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAppV1ConnectorServiceForceSyncResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIAppV1ConnectorServiceForceSyncResponse) GetForceSyncResponse() *shared.ForceSyncResponse {
	if c == nil {
		return nil
	}
	return c.ForceSyncResponse
}
