// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APIRequestSchemaV1RequestSchemaServiceUpdateRequest struct {
	RequestSchemaID                   string                                    `pathParam:"style=simple,explode=false,name=request_schema_id"`
	RequestSchemaServiceUpdateRequest *shared.RequestSchemaServiceUpdateRequest `request:"mediaType=application/json"`
}

func (c *C1APIRequestSchemaV1RequestSchemaServiceUpdateRequest) GetRequestSchemaID() string {
	if c == nil {
		return ""
	}
	return c.RequestSchemaID
}

func (c *C1APIRequestSchemaV1RequestSchemaServiceUpdateRequest) GetRequestSchemaServiceUpdateRequest() *shared.RequestSchemaServiceUpdateRequest {
	if c == nil {
		return nil
	}
	return c.RequestSchemaServiceUpdateRequest
}

type C1APIRequestSchemaV1RequestSchemaServiceUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	RequestSchemaServiceUpdateResponse *shared.RequestSchemaServiceUpdateResponse
}

func (c *C1APIRequestSchemaV1RequestSchemaServiceUpdateResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIRequestSchemaV1RequestSchemaServiceUpdateResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIRequestSchemaV1RequestSchemaServiceUpdateResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIRequestSchemaV1RequestSchemaServiceUpdateResponse) GetRequestSchemaServiceUpdateResponse() *shared.RequestSchemaServiceUpdateResponse {
	if c == nil {
		return nil
	}
	return c.RequestSchemaServiceUpdateResponse
}
