// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APISpendinsightsV1SpendInsightsServiceGetMySpendStatusRequest struct {
	AppID   *string `queryParam:"style=form,explode=true,name=app_id"`
	BlockID *string `queryParam:"style=form,explode=true,name=block_id"`
}

func (c *C1APISpendinsightsV1SpendInsightsServiceGetMySpendStatusRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *C1APISpendinsightsV1SpendInsightsServiceGetMySpendStatusRequest) GetBlockID() *string {
	if c == nil {
		return nil
	}
	return c.BlockID
}

// #region class-body-c1apispendinsightsv1spendinsightsservicegetmyspendstatusrequest
// #endregion class-body-c1apispendinsightsv1spendinsightsservicegetmyspendstatusrequest

type C1APISpendinsightsV1SpendInsightsServiceGetMySpendStatusResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// GetMySpendStatusResponse contains the caller's effective limits and optional denial.
	GetMySpendStatusResponse *shared.GetMySpendStatusResponse
}

func (c *C1APISpendinsightsV1SpendInsightsServiceGetMySpendStatusResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APISpendinsightsV1SpendInsightsServiceGetMySpendStatusResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APISpendinsightsV1SpendInsightsServiceGetMySpendStatusResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APISpendinsightsV1SpendInsightsServiceGetMySpendStatusResponse) GetGetMySpendStatusResponse() *shared.GetMySpendStatusResponse {
	if c == nil {
		return nil
	}
	return c.GetMySpendStatusResponse
}

// #region class-body-c1apispendinsightsv1spendinsightsservicegetmyspendstatusresponse
// #endregion class-body-c1apispendinsightsv1spendinsightsservicegetmyspendstatusresponse
