// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APIAppV1AppOwnersSetRequest struct {
	AppID               string                      `pathParam:"style=simple,explode=false,name=app_id"`
	SetAppOwnersRequest *shared.SetAppOwnersRequest `request:"mediaType=application/json"`
}

func (o *C1APIAppV1AppOwnersSetRequest) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

func (o *C1APIAppV1AppOwnersSetRequest) GetSetAppOwnersRequest() *shared.SetAppOwnersRequest {
	if o == nil {
		return nil
	}
	return o.SetAppOwnersRequest
}

type C1APIAppV1AppOwnersSetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The empty response message for setting the app owners.
	SetAppOwnersResponse *shared.SetAppOwnersResponse
}

func (o *C1APIAppV1AppOwnersSetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *C1APIAppV1AppOwnersSetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *C1APIAppV1AppOwnersSetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *C1APIAppV1AppOwnersSetResponse) GetSetAppOwnersResponse() *shared.SetAppOwnersResponse {
	if o == nil {
		return nil
	}
	return o.SetAppOwnersResponse
}
