// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APIWebhooksV1WebhooksServiceTestRequest struct {
	ID                         string                             `pathParam:"style=simple,explode=false,name=id"`
	WebhooksServiceTestRequest *shared.WebhooksServiceTestRequest `request:"mediaType=application/json"`
}

func (o *C1APIWebhooksV1WebhooksServiceTestRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *C1APIWebhooksV1WebhooksServiceTestRequest) GetWebhooksServiceTestRequest() *shared.WebhooksServiceTestRequest {
	if o == nil {
		return nil
	}
	return o.WebhooksServiceTestRequest
}

type C1APIWebhooksV1WebhooksServiceTestResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	WebhooksServiceTestResponse *shared.WebhooksServiceTestResponse
}

func (o *C1APIWebhooksV1WebhooksServiceTestResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *C1APIWebhooksV1WebhooksServiceTestResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *C1APIWebhooksV1WebhooksServiceTestResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *C1APIWebhooksV1WebhooksServiceTestResponse) GetWebhooksServiceTestResponse() *shared.WebhooksServiceTestResponse {
	if o == nil {
		return nil
	}
	return o.WebhooksServiceTestResponse
}
