// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APIFeedbackV1FeedbackServiceCreateFeedbackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	CreateFeedbackResponse *shared.CreateFeedbackResponse
}

func (c *C1APIFeedbackV1FeedbackServiceCreateFeedbackResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIFeedbackV1FeedbackServiceCreateFeedbackResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIFeedbackV1FeedbackServiceCreateFeedbackResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIFeedbackV1FeedbackServiceCreateFeedbackResponse) GetCreateFeedbackResponse() *shared.CreateFeedbackResponse {
	if c == nil {
		return nil
	}
	return c.CreateFeedbackResponse
}

// #region class-body-c1apifeedbackv1feedbackservicecreatefeedbackresponse
// #endregion class-body-c1apifeedbackv1feedbackservicecreatefeedbackresponse
