// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APIAppV1AppEntitlementOwnersListOwnerIDsRequest struct {
	AppID         string `pathParam:"style=simple,explode=false,name=app_id"`
	EntitlementID string `pathParam:"style=simple,explode=false,name=entitlement_id"`
}

func (c *C1APIAppV1AppEntitlementOwnersListOwnerIDsRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIAppV1AppEntitlementOwnersListOwnerIDsRequest) GetEntitlementID() string {
	if c == nil {
		return ""
	}
	return c.EntitlementID
}

type C1APIAppV1AppEntitlementOwnersListOwnerIDsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The response message for listing app entitlement owners IDs.
	ListAppEntitlementOwnerIDsResponse *shared.ListAppEntitlementOwnerIDsResponse
}

func (c *C1APIAppV1AppEntitlementOwnersListOwnerIDsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIAppV1AppEntitlementOwnersListOwnerIDsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIAppV1AppEntitlementOwnersListOwnerIDsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIAppV1AppEntitlementOwnersListOwnerIDsResponse) GetListAppEntitlementOwnerIDsResponse() *shared.ListAppEntitlementOwnerIDsResponse {
	if c == nil {
		return nil
	}
	return c.ListAppEntitlementOwnerIDsResponse
}
