// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APILlmGatewayV1ProviderCredentialServiceSetRequest struct {
	SlotID                       string                               `pathParam:"style=simple,explode=false,name=slot_id"`
	SetProviderCredentialRequest *shared.SetProviderCredentialRequest `request:"mediaType=application/json"`
}

func (c *C1APILlmGatewayV1ProviderCredentialServiceSetRequest) GetSlotID() string {
	if c == nil {
		return ""
	}
	return c.SlotID
}

func (c *C1APILlmGatewayV1ProviderCredentialServiceSetRequest) GetSetProviderCredentialRequest() *shared.SetProviderCredentialRequest {
	if c == nil {
		return nil
	}
	return c.SetProviderCredentialRequest
}

// #region class-body-c1apillmgatewayv1providercredentialservicesetrequest
// #endregion class-body-c1apillmgatewayv1providercredentialservicesetrequest

type C1APILlmGatewayV1ProviderCredentialServiceSetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	SetProviderCredentialResponse *shared.SetProviderCredentialResponse
}

func (c *C1APILlmGatewayV1ProviderCredentialServiceSetResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APILlmGatewayV1ProviderCredentialServiceSetResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APILlmGatewayV1ProviderCredentialServiceSetResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APILlmGatewayV1ProviderCredentialServiceSetResponse) GetSetProviderCredentialResponse() *shared.SetProviderCredentialResponse {
	if c == nil {
		return nil
	}
	return c.SetProviderCredentialResponse
}

// #region class-body-c1apillmgatewayv1providercredentialservicesetresponse
// #endregion class-body-c1apillmgatewayv1providercredentialservicesetresponse
