// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest struct {
	AppID                       string  `pathParam:"style=simple,explode=false,name=app_id"`
	ID                          string  `pathParam:"style=simple,explode=false,name=id"`
	EventID                     string  `pathParam:"style=simple,explode=false,name=event_id"`
	EventTime                   *string `queryParam:"style=form,explode=true,name=event_time"`
	IncludeParsedVerdictReasons *bool   `queryParam:"style=form,explode=true,name=include_parsed_verdict_reasons"`
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest) GetEventID() string {
	if c == nil {
		return ""
	}
	return c.EventID
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest) GetEventTime() *string {
	if c == nil {
		return nil
	}
	return c.EventTime
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventRequest) GetIncludeParsedVerdictReasons() *bool {
	if c == nil {
		return nil
	}
	return c.IncludeParsedVerdictReasons
}

// #region class-body-c1apiedgev1edgeservicegetegresstrafficeventrequest
// #endregion class-body-c1apiedgev1edgeservicegetegresstrafficeventrequest

type C1APIEdgeV1EdgeServiceGetEgressTrafficEventResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	EdgeServiceGetEgressTrafficEventResponse *shared.EdgeServiceGetEgressTrafficEventResponse
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *C1APIEdgeV1EdgeServiceGetEgressTrafficEventResponse) GetEdgeServiceGetEgressTrafficEventResponse() *shared.EdgeServiceGetEgressTrafficEventResponse {
	if c == nil {
		return nil
	}
	return c.EdgeServiceGetEgressTrafficEventResponse
}

// #region class-body-c1apiedgev1edgeservicegetegresstrafficeventresponse
// #endregion class-body-c1apiedgev1edgeservicegetegresstrafficeventresponse
