// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"net/http"
)

type C1APIAutomationsV1AutomationSearchServiceSearchAutomationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	SearchAutomationsResponse *shared.SearchAutomationsResponse
}

func (o *C1APIAutomationsV1AutomationSearchServiceSearchAutomationsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *C1APIAutomationsV1AutomationSearchServiceSearchAutomationsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *C1APIAutomationsV1AutomationSearchServiceSearchAutomationsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *C1APIAutomationsV1AutomationSearchServiceSearchAutomationsResponse) GetSearchAutomationsResponse() *shared.SearchAutomationsResponse {
	if o == nil {
		return nil
	}
	return o.SearchAutomationsResponse
}
