issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - copyloopvar
    - forcetypeassert
    - godot
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - usetesting
    - unconvert
    - unused
    - govet