version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt

linters:
  disable-all: true
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - forcetypeassert
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
