// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AddAppEntitlementOwnerResponse - The empty response message for adding an app entitlement owner.
type AddAppEntitlementOwnerResponse struct {
}
