// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SearchAppResourceTypesResponse - The SearchAppResourceTypesResponse message.
type SearchAppResourceTypesResponse struct {
	// The list field.
	List []AppResourceType `json:"list,omitempty"`
	// The nextPageToken field.
	NextPageToken *string `json:"nextPageToken,omitempty"`
	// The notificationToken field.
	NotificationToken *string `json:"notificationToken,omitempty"`
}
