// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserServiceGetResponse - The UserServiceGetResponse message.
type UserServiceGetResponse struct {
	// The expanded field.
	Expanded []map[string]interface{} `json:"expanded,omitempty"`
	// The UserView message.
	UserView *UserView `json:"userView,omitempty"`
}
