// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/internal/utils"
	"time"
)

// State - The state field.
type State string

const (
	StateSurfaceLifecycleStateUnspecified State = "SURFACE_LIFECYCLE_STATE_UNSPECIFIED"
	StateSurfaceLifecycleStateActive      State = "SURFACE_LIFECYCLE_STATE_ACTIVE"
	StateSurfaceLifecycleStateComplete    State = "SURFACE_LIFECYCLE_STATE_COMPLETE"
	StateSurfaceLifecycleStateDeleted     State = "SURFACE_LIFECYCLE_STATE_DELETED"
)

func (e State) ToPointer() *State {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *State) IsExact() bool {
	if e != nil {
		switch *e {
		case "SURFACE_LIFECYCLE_STATE_UNSPECIFIED", "SURFACE_LIFECYCLE_STATE_ACTIVE", "SURFACE_LIFECYCLE_STATE_COMPLETE", "SURFACE_LIFECYCLE_STATE_DELETED":
			return true
		}
	}
	return false
}

// A2UISurface represents a rendered UI surface within a conversation.
type A2UISurface struct {
	// The catalogId field.
	CatalogID *string `json:"catalogId,omitempty"`
	// The components field.
	Components []A2UIComponent `json:"components,omitempty"`
	// The conversationId field.
	ConversationID *string    `json:"conversationId,omitempty"`
	CreatedAt      *time.Time `json:"createdAt,omitempty"`
	// The dataModelJson field.
	DataModelJSON *string    `json:"dataModelJson,omitempty"`
	DeletedAt     *time.Time `json:"deletedAt,omitempty"`
	// The schemaVersion field.
	SchemaVersion *string `json:"schemaVersion,omitempty"`
	// The sendDataModel field.
	SendDataModel *bool `json:"sendDataModel,omitempty"`
	// The state field.
	State *State `json:"state,omitempty"`
	// The surfaceId field.
	SurfaceID *string `json:"surfaceId,omitempty"`
	// The tenantId field.
	TenantID  *string    `json:"tenantId,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

func (a A2UISurface) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *A2UISurface) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *A2UISurface) GetCatalogID() *string {
	if a == nil {
		return nil
	}
	return a.CatalogID
}

func (a *A2UISurface) GetComponents() []A2UIComponent {
	if a == nil {
		return nil
	}
	return a.Components
}

func (a *A2UISurface) GetConversationID() *string {
	if a == nil {
		return nil
	}
	return a.ConversationID
}

func (a *A2UISurface) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *A2UISurface) GetDataModelJSON() *string {
	if a == nil {
		return nil
	}
	return a.DataModelJSON
}

func (a *A2UISurface) GetDeletedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.DeletedAt
}

func (a *A2UISurface) GetSchemaVersion() *string {
	if a == nil {
		return nil
	}
	return a.SchemaVersion
}

func (a *A2UISurface) GetSendDataModel() *bool {
	if a == nil {
		return nil
	}
	return a.SendDataModel
}

func (a *A2UISurface) GetState() *State {
	if a == nil {
		return nil
	}
	return a.State
}

func (a *A2UISurface) GetSurfaceID() *string {
	if a == nil {
		return nil
	}
	return a.SurfaceID
}

func (a *A2UISurface) GetTenantID() *string {
	if a == nil {
		return nil
	}
	return a.TenantID
}

func (a *A2UISurface) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}

// #region class-body-a2uisurface
// #endregion class-body-a2uisurface
