// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The AccessReviewReportServiceListResponse message.
type AccessReviewReportServiceListResponse struct {
	// The list field.
	List []AccessReviewReport `json:"list,omitempty"`
	// The nextPageToken field.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

func (a *AccessReviewReportServiceListResponse) GetList() []AccessReviewReport {
	if a == nil {
		return nil
	}
	return a.List
}

func (a *AccessReviewReportServiceListResponse) GetNextPageToken() *string {
	if a == nil {
		return nil
	}
	return a.NextPageToken
}
