// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AccessReviewSetupEntitlementAndScopeServiceSetResponseExpanded - Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
type AccessReviewSetupEntitlementAndScopeServiceSetResponseExpanded struct {
}

// The AccessReviewSetupEntitlementAndScopeServiceSetResponse message.
type AccessReviewSetupEntitlementAndScopeServiceSetResponse struct {
	// Related objects requested via the expand mask.
	Expanded []AccessReviewSetupEntitlementAndScopeServiceSetResponseExpanded `json:"expanded,omitempty"`
	// The current list of setup entitlements for the campaign.
	List    []AccessReviewSetupEntitlementView `json:"list,omitempty"`
	ScopeV2 *AccessReviewScopeV2               `json:"scopeV2,omitempty"`
}

func (a *AccessReviewSetupEntitlementAndScopeServiceSetResponse) GetExpanded() []AccessReviewSetupEntitlementAndScopeServiceSetResponseExpanded {
	if a == nil {
		return nil
	}
	return a.Expanded
}

func (a *AccessReviewSetupEntitlementAndScopeServiceSetResponse) GetList() []AccessReviewSetupEntitlementView {
	if a == nil {
		return nil
	}
	return a.List
}

func (a *AccessReviewSetupEntitlementAndScopeServiceSetResponse) GetScopeV2() *AccessReviewScopeV2 {
	if a == nil {
		return nil
	}
	return a.ScopeV2
}
