// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/internal/utils"
	"time"
)

// IdentityMatching - The identityMatching field.
type IdentityMatching string

const (
	IdentityMatchingAppUserIdentityMatchingUnspecified IdentityMatching = "APP_USER_IDENTITY_MATCHING_UNSPECIFIED"
	IdentityMatchingAppUserIdentityMatchingStrict      IdentityMatching = "APP_USER_IDENTITY_MATCHING_STRICT"
	IdentityMatchingAppUserIdentityMatchingDisplayName IdentityMatching = "APP_USER_IDENTITY_MATCHING_DISPLAY_NAME"
)

func (e IdentityMatching) ToPointer() *IdentityMatching {
	return &e
}
func (e *IdentityMatching) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "APP_USER_IDENTITY_MATCHING_UNSPECIFIED":
		fallthrough
	case "APP_USER_IDENTITY_MATCHING_STRICT":
		fallthrough
	case "APP_USER_IDENTITY_MATCHING_DISPLAY_NAME":
		*e = IdentityMatching(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IdentityMatching: %v", v)
	}
}

// The App object provides all of the details for an app, as well as some configuration.
type App struct {
	// The ID of the Account named by AccountName.
	AppAccountID *string `json:"appAccountId,omitempty"`
	// The AccountName of the app. For example, AWS is AccountID, Github is Org Name, and Okta is Okta Subdomain.
	AppAccountName *string `json:"appAccountName,omitempty"`
	// The owners of the app.
	AppOwners []User `json:"appOwners,omitempty"`
	// The ID of the Certify Policy associated with this App.
	CertifyPolicyID *string `json:"certifyPolicyId,omitempty"`
	// The connectorVersion field.
	ConnectorVersion *int64     `json:"connectorVersion,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	// The ID for the default request catalog for this app.
	DefaultRequestCatalogID *string    `json:"defaultRequestCatalogId,omitempty"`
	DeletedAt               *time.Time `json:"deletedAt,omitempty"`
	// The app's description.
	Description *string `json:"description,omitempty"`
	// The app's display name.
	DisplayName *string `json:"displayName,omitempty"`
	FieldMask   *string `json:"fieldMask,omitempty"`
	// The ID of the Grant Policy associated with this App.
	GrantPolicyID *string `json:"grantPolicyId,omitempty"`
	// The URL of an icon to display for the app.
	IconURL *string `json:"iconUrl,omitempty"`
	// The ID of the app.
	ID *string `json:"id,omitempty"`
	// The identityMatching field.
	IdentityMatching *IdentityMatching `json:"identityMatching,omitempty"`
	// If you add instructions here, they will be shown to users in the access request form when requesting access for this app.
	Instructions *string `json:"instructions,omitempty"`
	// Specifies if the app is a directory.
	IsDirectory *bool `json:"isDirectory,omitempty"`
	// The isManuallyManaged field.
	IsManuallyManaged *bool `json:"isManuallyManaged,omitempty"`
	// The URL of a logo to display for the app.
	LogoURI *string `json:"logoUri,omitempty"`
	// The cost of an app per-seat, so that total cost can be calculated by the grant count.
	MonthlyCostUsd *int `json:"monthlyCostUsd,omitempty"`
	// The ID of the app that created this app, if any.
	ParentAppID *string `json:"parentAppId,omitempty"`
	// The ID of the Revoke Policy associated with this App.
	RevokePolicyID *string `json:"revokePolicyId,omitempty"`
	// The strictAccessEntitlementProvisioning field.
	StrictAccessEntitlementProvisioning *bool      `json:"strictAccessEntitlementProvisioning,omitempty"`
	UpdatedAt                           *time.Time `json:"updatedAt,omitempty"`
	// The number of users with grants to this app.
	UserCount *string `json:"userCount,omitempty"`
}

func (a App) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *App) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *App) GetAppAccountID() *string {
	if a == nil {
		return nil
	}
	return a.AppAccountID
}

func (a *App) GetAppAccountName() *string {
	if a == nil {
		return nil
	}
	return a.AppAccountName
}

func (a *App) GetAppOwners() []User {
	if a == nil {
		return nil
	}
	return a.AppOwners
}

func (a *App) GetCertifyPolicyID() *string {
	if a == nil {
		return nil
	}
	return a.CertifyPolicyID
}

func (a *App) GetConnectorVersion() *int64 {
	if a == nil {
		return nil
	}
	return a.ConnectorVersion
}

func (a *App) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *App) GetDefaultRequestCatalogID() *string {
	if a == nil {
		return nil
	}
	return a.DefaultRequestCatalogID
}

func (a *App) GetDeletedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.DeletedAt
}

func (a *App) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *App) GetDisplayName() *string {
	if a == nil {
		return nil
	}
	return a.DisplayName
}

func (a *App) GetFieldMask() *string {
	if a == nil {
		return nil
	}
	return a.FieldMask
}

func (a *App) GetGrantPolicyID() *string {
	if a == nil {
		return nil
	}
	return a.GrantPolicyID
}

func (a *App) GetIconURL() *string {
	if a == nil {
		return nil
	}
	return a.IconURL
}

func (a *App) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *App) GetIdentityMatching() *IdentityMatching {
	if a == nil {
		return nil
	}
	return a.IdentityMatching
}

func (a *App) GetInstructions() *string {
	if a == nil {
		return nil
	}
	return a.Instructions
}

func (a *App) GetIsDirectory() *bool {
	if a == nil {
		return nil
	}
	return a.IsDirectory
}

func (a *App) GetIsManuallyManaged() *bool {
	if a == nil {
		return nil
	}
	return a.IsManuallyManaged
}

func (a *App) GetLogoURI() *string {
	if a == nil {
		return nil
	}
	return a.LogoURI
}

func (a *App) GetMonthlyCostUsd() *int {
	if a == nil {
		return nil
	}
	return a.MonthlyCostUsd
}

func (a *App) GetParentAppID() *string {
	if a == nil {
		return nil
	}
	return a.ParentAppID
}

func (a *App) GetRevokePolicyID() *string {
	if a == nil {
		return nil
	}
	return a.RevokePolicyID
}

func (a *App) GetStrictAccessEntitlementProvisioning() *bool {
	if a == nil {
		return nil
	}
	return a.StrictAccessEntitlementProvisioning
}

func (a *App) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}

func (a *App) GetUserCount() *string {
	if a == nil {
		return nil
	}
	return a.UserCount
}

// AppInput - The App object provides all of the details for an app, as well as some configuration.
type AppInput struct {
	// The ID of the Certify Policy associated with this App.
	CertifyPolicyID *string `json:"certifyPolicyId,omitempty"`
	// The connectorVersion field.
	ConnectorVersion *int64     `json:"connectorVersion,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	// The ID for the default request catalog for this app.
	DefaultRequestCatalogID *string    `json:"defaultRequestCatalogId,omitempty"`
	DeletedAt               *time.Time `json:"deletedAt,omitempty"`
	// The app's description.
	Description *string `json:"description,omitempty"`
	// The app's display name.
	DisplayName *string `json:"displayName,omitempty"`
	FieldMask   *string `json:"fieldMask,omitempty"`
	// The ID of the Grant Policy associated with this App.
	GrantPolicyID *string `json:"grantPolicyId,omitempty"`
	// The URL of an icon to display for the app.
	IconURL *string `json:"iconUrl,omitempty"`
	// The identityMatching field.
	IdentityMatching *IdentityMatching `json:"identityMatching,omitempty"`
	// If you add instructions here, they will be shown to users in the access request form when requesting access for this app.
	Instructions *string `json:"instructions,omitempty"`
	// The isManuallyManaged field.
	IsManuallyManaged *bool `json:"isManuallyManaged,omitempty"`
	// The cost of an app per-seat, so that total cost can be calculated by the grant count.
	MonthlyCostUsd *int `json:"monthlyCostUsd,omitempty"`
	// The ID of the Revoke Policy associated with this App.
	RevokePolicyID *string `json:"revokePolicyId,omitempty"`
	// The strictAccessEntitlementProvisioning field.
	StrictAccessEntitlementProvisioning *bool      `json:"strictAccessEntitlementProvisioning,omitempty"`
	UpdatedAt                           *time.Time `json:"updatedAt,omitempty"`
}

func (a AppInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AppInput) GetCertifyPolicyID() *string {
	if a == nil {
		return nil
	}
	return a.CertifyPolicyID
}

func (a *AppInput) GetConnectorVersion() *int64 {
	if a == nil {
		return nil
	}
	return a.ConnectorVersion
}

func (a *AppInput) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AppInput) GetDefaultRequestCatalogID() *string {
	if a == nil {
		return nil
	}
	return a.DefaultRequestCatalogID
}

func (a *AppInput) GetDeletedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.DeletedAt
}

func (a *AppInput) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AppInput) GetDisplayName() *string {
	if a == nil {
		return nil
	}
	return a.DisplayName
}

func (a *AppInput) GetFieldMask() *string {
	if a == nil {
		return nil
	}
	return a.FieldMask
}

func (a *AppInput) GetGrantPolicyID() *string {
	if a == nil {
		return nil
	}
	return a.GrantPolicyID
}

func (a *AppInput) GetIconURL() *string {
	if a == nil {
		return nil
	}
	return a.IconURL
}

func (a *AppInput) GetIdentityMatching() *IdentityMatching {
	if a == nil {
		return nil
	}
	return a.IdentityMatching
}

func (a *AppInput) GetInstructions() *string {
	if a == nil {
		return nil
	}
	return a.Instructions
}

func (a *AppInput) GetIsManuallyManaged() *bool {
	if a == nil {
		return nil
	}
	return a.IsManuallyManaged
}

func (a *AppInput) GetMonthlyCostUsd() *int {
	if a == nil {
		return nil
	}
	return a.MonthlyCostUsd
}

func (a *AppInput) GetRevokePolicyID() *string {
	if a == nil {
		return nil
	}
	return a.RevokePolicyID
}

func (a *AppInput) GetStrictAccessEntitlementProvisioning() *bool {
	if a == nil {
		return nil
	}
	return a.StrictAccessEntitlementProvisioning
}

func (a *AppInput) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}
