// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AppEntitlementView - The app entitlement view contains the serialized app entitlement and paths to objects referenced by the app entitlement.
type AppEntitlementView struct {
	AppEntitlement    *AppEntitlement         `json:"appEntitlement,omitempty"`
	ObjectPermissions *ActorObjectPermissions `json:"objectPermissions,omitempty"`
}

func (a *AppEntitlementView) GetAppEntitlement() *AppEntitlement {
	if a == nil {
		return nil
	}
	return a.AppEntitlement
}

func (a *AppEntitlementView) GetObjectPermissions() *ActorObjectPermissions {
	if a == nil {
		return nil
	}
	return a.ObjectPermissions
}
