// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AppEntitlementSearchServiceSearchReachableResourcesForUserResponse - SearchReachableResourcesForUser response. Resources are deduplicated: a
//
//	resource reachable through more than one grant or entitlement appears once.
type AppEntitlementSearchServiceSearchReachableResourcesForUserResponse struct {
	// The reachable resources, one GraphNode (type = GRAPH_NODE_TYPE_RESOURCE)
	//  per distinct resource. Uses the same node representation as SearchGraph.
	List []GraphNode `json:"list,omitempty"`
	// Token for fetching the next page of results.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

func (a *AppEntitlementSearchServiceSearchReachableResourcesForUserResponse) GetList() []GraphNode {
	if a == nil {
		return nil
	}
	return a.List
}

func (a *AppEntitlementSearchServiceSearchReachableResourcesForUserResponse) GetNextPageToken() *string {
	if a == nil {
		return nil
	}
	return a.NextPageToken
}
