// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/internal/utils"
	"time"
)

// The AppEntitlementUserView (aka grant view) describes the relationship between an app user and an entitlement. They have more recently been referred to as grants.
type AppEntitlementUserView struct {
	AppEntitlementUserBindingCreatedAt     *time.Time `json:"appEntitlementUserBindingCreatedAt,omitempty"`
	AppEntitlementUserBindingDeprovisionAt *time.Time `json:"appEntitlementUserBindingDeprovisionAt,omitempty"`
	// The AppUserView contains an app user as well as paths for apps, identity users, and last usage in expanded arrays.
	AppUserView *AppUserView `json:"appUser,omitempty"`
	// List of sources for the grant, ie. groups, roles, etc.
	GrantSources []AppEntitlementRef `json:"grantSources,omitempty"`
}

func (a AppEntitlementUserView) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppEntitlementUserView) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AppEntitlementUserView) GetAppEntitlementUserBindingCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.AppEntitlementUserBindingCreatedAt
}

func (a *AppEntitlementUserView) GetAppEntitlementUserBindingDeprovisionAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.AppEntitlementUserBindingDeprovisionAt
}

func (a *AppEntitlementUserView) GetAppUserView() *AppUserView {
	if a == nil {
		return nil
	}
	return a.AppUserView
}

func (a *AppEntitlementUserView) GetGrantSources() []AppEntitlementRef {
	if a == nil {
		return nil
	}
	return a.GrantSources
}
