// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The AppSecretRef message.
type AppSecretRef struct {
	// The appId field.
	AppID *string `json:"appId,omitempty"`
	// The appResourceTypeId field.
	AppResourceTypeID *string `json:"appResourceTypeId,omitempty"`
	// The id field.
	ID *string `json:"id,omitempty"`
}

func (a *AppSecretRef) GetAppID() *string {
	if a == nil {
		return nil
	}
	return a.AppID
}

func (a *AppSecretRef) GetAppResourceTypeID() *string {
	if a == nil {
		return nil
	}
	return a.AppResourceTypeID
}

func (a *AppSecretRef) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}
