// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AuthzenServerServiceDeleteRequest deletes the AuthZEN server for an app.
type AuthzenServerServiceDeleteRequest struct {
}
