// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e9f05a06d265

package shared

// AutomationsDeleteAutomationRequest - The DeleteAutomationRequest message.
type AutomationsDeleteAutomationRequest struct {
}
