// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CompositeFormat - Wire format the provider expects. Defaults to
//
//	FORMAT_JSON_OBJECT.
type CompositeFormat string

const (
	CompositeFormatFormatJSONObject          CompositeFormat = "FORMAT_JSON_OBJECT"
	CompositeFormatFormatColonSeparated      CompositeFormat = "FORMAT_COLON_SEPARATED"
	CompositeFormatFormatUnderscoreSeparated CompositeFormat = "FORMAT_UNDERSCORE_SEPARATED"
)

func (e CompositeFormat) ToPointer() *CompositeFormat {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CompositeFormat) IsExact() bool {
	if e != nil {
		switch *e {
		case "FORMAT_JSON_OBJECT", "FORMAT_COLON_SEPARATED", "FORMAT_UNDERSCORE_SEPARATED":
			return true
		}
	}
	return false
}

// Composite import IDs combine values from multiple component fields
//
//	per the declared `format`.
type Composite struct {
	// Component fields, in the order they participate in the import
	//  ID.
	Fields []CompositeField `json:"fields,omitempty"`
	// Wire format the provider expects. Defaults to
	//  FORMAT_JSON_OBJECT.
	Format *CompositeFormat `json:"format,omitempty"`
}

func (c *Composite) GetFields() []CompositeField {
	if c == nil {
		return nil
	}
	return c.Fields
}

func (c *Composite) GetFormat() *CompositeFormat {
	if c == nil {
		return nil
	}
	return c.Format
}
