// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e2fe1071efe8

package shared

// ConnectorActionRefInput - ConnectorActionRef describes dispatch through a connector's built-in
//
//	GrantManagerService Grant / Revoke RPC — i.e. the default connector
//	operation, used for synthesized tickets like scope-role requests.
type ConnectorActionRefInput struct {
}
