// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ConnectorField - The Field message.
//
// This message contains a oneof named field. Only a single field of the following list may be set at a time:
//   - str
//   - select
//   - random
//   - import
//   - oauth2
//   - readOnly
//   - options
//   - checkbox
//   - secret
//   - strList
//   - text
//   - keyValue
//   - stringMap
type ConnectorField struct {
	// Optional. Additional placeholder text for the field
	//  In cases where a single placeholder is not enough to describe the field
	AdditionalPlaceholder *string `json:"additionalPlaceholder,omitempty"`
	// The CheckboxField message.
	ConnectorCheckboxField *ConnectorCheckboxField `json:"checkbox,omitempty"`
	// The dependsOnFields field.
	DependsOnFields []string `json:"dependsOnFields,omitempty"`
	// Human-readable label for this Field
	DisplayName *string `json:"displayName,omitempty"`
	// empty or https URL
	HelpURL *string `json:"helpUrl,omitempty"`
	// The ImportField message.
	ImportField *ImportField `json:"import,omitempty"`
	// The KeyValueField message.
	KeyValueField *KeyValueField `json:"keyValue,omitempty"`
	// Must not start with `C1_` and match [a-zA-Z0-9_]{2,64}.  Must be unique within a connector.
	Name *string `json:"name,omitempty"`
	// The OAuth2Field message.
	OAuth2Field *OAuth2Field1 `json:"oauth2,omitempty"`
	// The OptionsField message.
	OptionsField *OptionsField `json:"options,omitempty"`
	// The placeholder field.
	Placeholder *string `json:"placeholder,omitempty"`
	// The postCreate field.
	PostCreate *bool `json:"postCreate,omitempty"`
	// The RandomStringField message.
	RandomStringField *RandomStringField `json:"random,omitempty"`
	// The ReadOnlyField message.
	ReadOnlyField *ReadOnlyField `json:"readOnly,omitempty"`
	// The RotatableSecretField message.
	RotatableSecretField *RotatableSecretField `json:"secret,omitempty"`
	// The SelectField message.
	ConnectorSelectField *ConnectorSelectField `json:"select,omitempty"`
	// The StringField message.
	ConnectorStringField *ConnectorStringField `json:"str,omitempty"`
	// The StringListField message.
	StringListField *StringListField `json:"strList,omitempty"`
	// The StringMapField message.
	ConnectorStringMapField *ConnectorStringMapField `json:"stringMap,omitempty"`
	// The TextField message.
	ConnectorTextField *ConnectorTextField `json:"text,omitempty"`
}

func (c *ConnectorField) GetAdditionalPlaceholder() *string {
	if c == nil {
		return nil
	}
	return c.AdditionalPlaceholder
}

func (c *ConnectorField) GetConnectorCheckboxField() *ConnectorCheckboxField {
	if c == nil {
		return nil
	}
	return c.ConnectorCheckboxField
}

func (c *ConnectorField) GetDependsOnFields() []string {
	if c == nil {
		return nil
	}
	return c.DependsOnFields
}

func (c *ConnectorField) GetDisplayName() *string {
	if c == nil {
		return nil
	}
	return c.DisplayName
}

func (c *ConnectorField) GetHelpURL() *string {
	if c == nil {
		return nil
	}
	return c.HelpURL
}

func (c *ConnectorField) GetImportField() *ImportField {
	if c == nil {
		return nil
	}
	return c.ImportField
}

func (c *ConnectorField) GetKeyValueField() *KeyValueField {
	if c == nil {
		return nil
	}
	return c.KeyValueField
}

func (c *ConnectorField) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *ConnectorField) GetOAuth2Field() *OAuth2Field1 {
	if c == nil {
		return nil
	}
	return c.OAuth2Field
}

func (c *ConnectorField) GetOptionsField() *OptionsField {
	if c == nil {
		return nil
	}
	return c.OptionsField
}

func (c *ConnectorField) GetPlaceholder() *string {
	if c == nil {
		return nil
	}
	return c.Placeholder
}

func (c *ConnectorField) GetPostCreate() *bool {
	if c == nil {
		return nil
	}
	return c.PostCreate
}

func (c *ConnectorField) GetRandomStringField() *RandomStringField {
	if c == nil {
		return nil
	}
	return c.RandomStringField
}

func (c *ConnectorField) GetReadOnlyField() *ReadOnlyField {
	if c == nil {
		return nil
	}
	return c.ReadOnlyField
}

func (c *ConnectorField) GetRotatableSecretField() *RotatableSecretField {
	if c == nil {
		return nil
	}
	return c.RotatableSecretField
}

func (c *ConnectorField) GetConnectorSelectField() *ConnectorSelectField {
	if c == nil {
		return nil
	}
	return c.ConnectorSelectField
}

func (c *ConnectorField) GetConnectorStringField() *ConnectorStringField {
	if c == nil {
		return nil
	}
	return c.ConnectorStringField
}

func (c *ConnectorField) GetStringListField() *StringListField {
	if c == nil {
		return nil
	}
	return c.StringListField
}

func (c *ConnectorField) GetConnectorStringMapField() *ConnectorStringMapField {
	if c == nil {
		return nil
	}
	return c.ConnectorStringMapField
}

func (c *ConnectorField) GetConnectorTextField() *ConnectorTextField {
	if c == nil {
		return nil
	}
	return c.ConnectorTextField
}
