// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/internal/utils"
)

// Config - Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
type Config struct {
	// The type of the serialized message.
	AtType               *string `json:"@type,omitempty"`
	AdditionalProperties any     `additionalProperties:"true" json:"-"`
}

func (c Config) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Config) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Config) GetAtType() *string {
	if o == nil {
		return nil
	}
	return o.AtType
}

func (o *Config) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

// The ConnectorServiceCreateRequest message.
type ConnectorServiceCreateRequest struct {
	// The catalogId field.
	CatalogID *string `json:"catalogId,omitempty"`
	// Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
	Config *Config `json:"config,omitempty"`
	// The description field.
	Description *string `json:"description,omitempty"`
	// The userIds field.
	UserIds []string `json:"userIds,omitempty"`
}

func (o *ConnectorServiceCreateRequest) GetCatalogID() *string {
	if o == nil {
		return nil
	}
	return o.CatalogID
}

func (o *ConnectorServiceCreateRequest) GetConfig() *Config {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *ConnectorServiceCreateRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ConnectorServiceCreateRequest) GetUserIds() []string {
	if o == nil {
		return nil
	}
	return o.UserIds
}
