// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The ConnectorIssuesPreference message.
type ConnectorIssuesPreference struct {
	// The enabled field.
	Enabled *bool `json:"enabled,omitempty"`
	// The locked field.
	Locked *bool `json:"locked,omitempty"`
}

func (c *ConnectorIssuesPreference) GetEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.Enabled
}

func (c *ConnectorIssuesPreference) GetLocked() *bool {
	if c == nil {
		return nil
	}
	return c.Locked
}
