// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ConnectorProvision - Indicates that a connector should perform the provisioning. This object has no fields.
//
// This message contains a oneof named provision_type. Only a single field of the following list may be set at a time:
//   - defaultBehavior
//   - account
//   - deleteAccount
type ConnectorProvision struct {
	// The AccountProvision message.
	//
	// This message contains a oneof named storage_type. Only a single field of the following list may be set at a time:
	//   - saveToVault
	//   - doNotSave
	//
	AccountProvision *AccountProvision `json:"account,omitempty"`
	// The DefaultBehavior message.
	DefaultBehavior *DefaultBehavior `json:"defaultBehavior,omitempty"`
	// The DeleteAccount message.
	DeleteAccount *DeleteAccount `json:"deleteAccount,omitempty"`
}

func (c *ConnectorProvision) GetAccountProvision() *AccountProvision {
	if c == nil {
		return nil
	}
	return c.AccountProvision
}

func (c *ConnectorProvision) GetDefaultBehavior() *DefaultBehavior {
	if c == nil {
		return nil
	}
	return c.DefaultBehavior
}

func (c *ConnectorProvision) GetDeleteAccount() *DeleteAccount {
	if c == nil {
		return nil
	}
	return c.DeleteAccount
}
