// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/terraform-provider-conductorone/v2/internal/sdk/internal/utils"
	"time"
)

// Contacts represents the contact configuration for an organization.
type Contacts struct {
	// Email addresses of billing contacts for this organization.
	BillingEmails []string   `json:"billingEmails,omitempty"`
	CreatedAt     *time.Time `json:"createdAt,omitempty"`
	// Email addresses of operations contacts for this organization.
	OperationsEmails []string `json:"operationsEmails,omitempty"`
	// Email addresses of security contacts for this organization.
	SecurityEmails []string   `json:"securityEmails,omitempty"`
	UpdatedAt      *time.Time `json:"updatedAt,omitempty"`
}

func (c Contacts) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Contacts) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Contacts) GetBillingEmails() []string {
	if c == nil {
		return nil
	}
	return c.BillingEmails
}

func (c *Contacts) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *Contacts) GetOperationsEmails() []string {
	if c == nil {
		return nil
	}
	return c.OperationsEmails
}

func (c *Contacts) GetSecurityEmails() []string {
	if c == nil {
		return nil
	}
	return c.SecurityEmails
}

func (c *Contacts) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}
