// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// CreateAppEntitlementMonitorBindingRequestEntitlementGroup - The entitlementGroup field.
type CreateAppEntitlementMonitorBindingRequestEntitlementGroup string

const (
	CreateAppEntitlementMonitorBindingRequestEntitlementGroupEntitlementGroupUnspecified CreateAppEntitlementMonitorBindingRequestEntitlementGroup = "ENTITLEMENT_GROUP_UNSPECIFIED"
	CreateAppEntitlementMonitorBindingRequestEntitlementGroupEntitlementGroupA           CreateAppEntitlementMonitorBindingRequestEntitlementGroup = "ENTITLEMENT_GROUP_A"
	CreateAppEntitlementMonitorBindingRequestEntitlementGroupEntitlementGroupB           CreateAppEntitlementMonitorBindingRequestEntitlementGroup = "ENTITLEMENT_GROUP_B"
)

func (e CreateAppEntitlementMonitorBindingRequestEntitlementGroup) ToPointer() *CreateAppEntitlementMonitorBindingRequestEntitlementGroup {
	return &e
}
func (e *CreateAppEntitlementMonitorBindingRequestEntitlementGroup) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ENTITLEMENT_GROUP_UNSPECIFIED":
		fallthrough
	case "ENTITLEMENT_GROUP_A":
		fallthrough
	case "ENTITLEMENT_GROUP_B":
		*e = CreateAppEntitlementMonitorBindingRequestEntitlementGroup(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateAppEntitlementMonitorBindingRequestEntitlementGroup: %v", v)
	}
}

// The CreateAppEntitlementMonitorBindingRequest message.
type CreateAppEntitlementMonitorBindingRequest struct {
	// The appEntitlementId field.
	AppEntitlementID *string `json:"appEntitlementId,omitempty"`
	// The appId field.
	AppID *string `json:"appId,omitempty"`
	// The entitlementGroup field.
	EntitlementGroup *CreateAppEntitlementMonitorBindingRequestEntitlementGroup `json:"entitlementGroup,omitempty"`
	// The monitorId field.
	MonitorID *string `json:"monitorId,omitempty"`
}

func (o *CreateAppEntitlementMonitorBindingRequest) GetAppEntitlementID() *string {
	if o == nil {
		return nil
	}
	return o.AppEntitlementID
}

func (o *CreateAppEntitlementMonitorBindingRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *CreateAppEntitlementMonitorBindingRequest) GetEntitlementGroup() *CreateAppEntitlementMonitorBindingRequestEntitlementGroup {
	if o == nil {
		return nil
	}
	return o.EntitlementGroup
}

func (o *CreateAppEntitlementMonitorBindingRequest) GetMonitorID() *string {
	if o == nil {
		return nil
	}
	return o.MonitorID
}
