// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The CreateBundleAutomationRequest message.
//
// This message contains a oneof named conditions. Only a single field of the following list may be set at a time:
//   - entitlements
type CreateBundleAutomationRequest struct {
	// The createTasks field.
	CreateTasks *bool `json:"createTasks,omitempty"`
	// The disableCircuitBreaker field.
	DisableCircuitBreaker *bool `json:"disableCircuitBreaker,omitempty"`
	// The enabled field.
	Enabled *bool `json:"enabled,omitempty"`
	// The BundleAutomationRuleEntitlement message.
	BundleAutomationRuleEntitlement *BundleAutomationRuleEntitlement `json:"entitlements,omitempty"`
}

func (c *CreateBundleAutomationRequest) GetCreateTasks() *bool {
	if c == nil {
		return nil
	}
	return c.CreateTasks
}

func (c *CreateBundleAutomationRequest) GetDisableCircuitBreaker() *bool {
	if c == nil {
		return nil
	}
	return c.DisableCircuitBreaker
}

func (c *CreateBundleAutomationRequest) GetEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.Enabled
}

func (c *CreateBundleAutomationRequest) GetBundleAutomationRuleEntitlement() *BundleAutomationRuleEntitlement {
	if c == nil {
		return nil
	}
	return c.BundleAutomationRuleEntitlement
}
