// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CreateConnectorUserOwnerRequest is the request for creating a user ownership source on a connector.
type CreateConnectorUserOwnerRequest struct {
	UserRef *UserRef `json:"userRef,omitempty"`
}

func (c *CreateConnectorUserOwnerRequest) GetUserRef() *UserRef {
	if c == nil {
		return nil
	}
	return c.UserRef
}
