// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CreateConnectorUserOwnerResponse is the response for creating a user ownership source on a connector.
type CreateConnectorUserOwnerResponse struct {
	// ConnectorOwnerUser represents a user ownership source for a connector.
	ConnectorOwnerUser *ConnectorOwnerUser `json:"connectorOwnerUser,omitempty"`
}

func (c *CreateConnectorUserOwnerResponse) GetConnectorOwnerUser() *ConnectorOwnerUser {
	if c == nil {
		return nil
	}
	return c.ConnectorOwnerUser
}
