// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CreateAppResourceEntitlementOwnerRequest is the request for creating an entitlement ownership source on a resource.
type CreateAppResourceEntitlementOwnerRequest struct {
	// The AppEntitlementRef message.
	AppEntitlementRef *AppEntitlementRef `json:"appEntitlementRef,omitempty"`
}

func (c *CreateAppResourceEntitlementOwnerRequest) GetAppEntitlementRef() *AppEntitlementRef {
	if c == nil {
		return nil
	}
	return c.AppEntitlementRef
}
