// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The CredentialInventoryPolicyServiceGetResponse message.
type CredentialInventoryPolicyServiceGetResponse struct {
	CredentialInventoryPolicy *CredentialInventoryPolicy `json:"credentialInventoryPolicy,omitempty"`
}

func (c *CredentialInventoryPolicyServiceGetResponse) GetCredentialInventoryPolicy() *CredentialInventoryPolicy {
	if c == nil {
		return nil
	}
	return c.CredentialInventoryPolicy
}
