// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// DecoyAccessTokenInput mints a session access-token decoy under an
//
//	existing User.
type DecoyAccessTokenInput struct {
	ExpiresIn *string `json:"expiresIn,omitempty"`
	// Existing User the access token's subject claim references.
	SubjectUserID *string `json:"subjectUserId,omitempty"`
}

func (d *DecoyAccessTokenInput) GetExpiresIn() *string {
	if d == nil {
		return nil
	}
	return d.ExpiresIn
}

func (d *DecoyAccessTokenInput) GetSubjectUserID() *string {
	if d == nil {
		return nil
	}
	return d.SubjectUserID
}
