// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// DeleteAppUserOwnerResponse - DeleteUserOwnerResponse is the empty response for deleting a user ownership source.
type DeleteAppUserOwnerResponse struct {
}
