// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/internal/utils"
	"time"
)

// DenialFiltersAuthorityKind - Optional authority type to match. Set authority_id with this field.
type DenialFiltersAuthorityKind string

const (
	DenialFiltersAuthorityKindAuthorityKindUnspecified        DenialFiltersAuthorityKind = "AUTHORITY_KIND_UNSPECIFIED"
	DenialFiltersAuthorityKindAuthorityKindFundPolicy         DenialFiltersAuthorityKind = "AUTHORITY_KIND_FUND_POLICY"
	DenialFiltersAuthorityKindAuthorityKindFundAssignment     DenialFiltersAuthorityKind = "AUTHORITY_KIND_FUND_ASSIGNMENT"
	DenialFiltersAuthorityKindAuthorityKindFundRule           DenialFiltersAuthorityKind = "AUTHORITY_KIND_FUND_RULE"
	DenialFiltersAuthorityKindAuthorityKindTenantAppCap       DenialFiltersAuthorityKind = "AUTHORITY_KIND_TENANT_APP_CAP"
	DenialFiltersAuthorityKindAuthorityKindSubjectAppLimit    DenialFiltersAuthorityKind = "AUTHORITY_KIND_SUBJECT_APP_LIMIT"
	DenialFiltersAuthorityKindAuthorityKindEntitlementBinding DenialFiltersAuthorityKind = "AUTHORITY_KIND_ENTITLEMENT_BINDING"
	DenialFiltersAuthorityKindAuthorityKindAppUser            DenialFiltersAuthorityKind = "AUTHORITY_KIND_APP_USER"
	DenialFiltersAuthorityKindAuthorityKindUser               DenialFiltersAuthorityKind = "AUTHORITY_KIND_USER"
)

func (e DenialFiltersAuthorityKind) ToPointer() *DenialFiltersAuthorityKind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DenialFiltersAuthorityKind) IsExact() bool {
	if e != nil {
		switch *e {
		case "AUTHORITY_KIND_UNSPECIFIED", "AUTHORITY_KIND_FUND_POLICY", "AUTHORITY_KIND_FUND_ASSIGNMENT", "AUTHORITY_KIND_FUND_RULE", "AUTHORITY_KIND_TENANT_APP_CAP", "AUTHORITY_KIND_SUBJECT_APP_LIMIT", "AUTHORITY_KIND_ENTITLEMENT_BINDING", "AUTHORITY_KIND_APP_USER", "AUTHORITY_KIND_USER":
			return true
		}
	}
	return false
}

// DenialFiltersScopeKind - Optional budget scope to match.
type DenialFiltersScopeKind string

const (
	DenialFiltersScopeKindSpendBlockScopeKindUnspecified DenialFiltersScopeKind = "SPEND_BLOCK_SCOPE_KIND_UNSPECIFIED"
	DenialFiltersScopeKindSpendBlockScopeKindTenant      DenialFiltersScopeKind = "SPEND_BLOCK_SCOPE_KIND_TENANT"
	DenialFiltersScopeKindSpendBlockScopeKindSubject     DenialFiltersScopeKind = "SPEND_BLOCK_SCOPE_KIND_SUBJECT"
	DenialFiltersScopeKindSpendBlockScopeKindApp         DenialFiltersScopeKind = "SPEND_BLOCK_SCOPE_KIND_APP"
	DenialFiltersScopeKindSpendBlockScopeKindSubjectApp  DenialFiltersScopeKind = "SPEND_BLOCK_SCOPE_KIND_SUBJECT_APP"
)

func (e DenialFiltersScopeKind) ToPointer() *DenialFiltersScopeKind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DenialFiltersScopeKind) IsExact() bool {
	if e != nil {
		switch *e {
		case "SPEND_BLOCK_SCOPE_KIND_UNSPECIFIED", "SPEND_BLOCK_SCOPE_KIND_TENANT", "SPEND_BLOCK_SCOPE_KIND_SUBJECT", "SPEND_BLOCK_SCOPE_KIND_APP", "SPEND_BLOCK_SCOPE_KIND_SUBJECT_APP":
			return true
		}
	}
	return false
}

// DenialFiltersState - Optional current episode state to match.
type DenialFiltersState string

const (
	DenialFiltersStateSpendBlockStateUnspecified DenialFiltersState = "SPEND_BLOCK_STATE_UNSPECIFIED"
	DenialFiltersStateSpendBlockStateOpen        DenialFiltersState = "SPEND_BLOCK_STATE_OPEN"
	DenialFiltersStateSpendBlockStateClosed      DenialFiltersState = "SPEND_BLOCK_STATE_CLOSED"
)

func (e DenialFiltersState) ToPointer() *DenialFiltersState {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DenialFiltersState) IsExact() bool {
	if e != nil {
		switch *e {
		case "SPEND_BLOCK_STATE_UNSPECIFIED", "SPEND_BLOCK_STATE_OPEN", "SPEND_BLOCK_STATE_CLOSED":
			return true
		}
	}
	return false
}

// DenialFilters selects budget-denial episodes.
type DenialFilters struct {
	// Optional authority ID to match. Set authority_kind with this field.
	AuthorityID *string `json:"authorityId,omitempty"`
	// Optional authority type to match. Set authority_id with this field.
	AuthorityKind *DenialFiltersAuthorityKind `json:"authorityKind,omitempty"`
	// Optional current user departments to match. Only subject-scoped denials
	//  with a live, non-deleted user row can match; organization-scoped,
	//  application-scoped, missing-user, and deleted-user denials are excluded.
	//  Department is resolved from scope_user_id at read time, not captured from
	//  the denial event.
	Departments []string   `json:"departments,omitempty"`
	EndTime     *time.Time `json:"endTime,omitempty"`
	// Optional application scope ID to match.
	ScopeAppID *string `json:"scopeAppId,omitempty"`
	// Optional budget scope to match.
	ScopeKind *DenialFiltersScopeKind `json:"scopeKind,omitempty"`
	// Optional user scope ID to match.
	ScopeUserID *string    `json:"scopeUserId,omitempty"`
	StartTime   *time.Time `json:"startTime,omitempty"`
	// Optional current episode state to match.
	State *DenialFiltersState `json:"state,omitempty"`
}

func (d DenialFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DenialFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DenialFilters) GetAuthorityID() *string {
	if d == nil {
		return nil
	}
	return d.AuthorityID
}

func (d *DenialFilters) GetAuthorityKind() *DenialFiltersAuthorityKind {
	if d == nil {
		return nil
	}
	return d.AuthorityKind
}

func (d *DenialFilters) GetDepartments() []string {
	if d == nil {
		return nil
	}
	return d.Departments
}

func (d *DenialFilters) GetEndTime() *time.Time {
	if d == nil {
		return nil
	}
	return d.EndTime
}

func (d *DenialFilters) GetScopeAppID() *string {
	if d == nil {
		return nil
	}
	return d.ScopeAppID
}

func (d *DenialFilters) GetScopeKind() *DenialFiltersScopeKind {
	if d == nil {
		return nil
	}
	return d.ScopeKind
}

func (d *DenialFilters) GetScopeUserID() *string {
	if d == nil {
		return nil
	}
	return d.ScopeUserID
}

func (d *DenialFilters) GetStartTime() *time.Time {
	if d == nil {
		return nil
	}
	return d.StartTime
}

func (d *DenialFilters) GetState() *DenialFiltersState {
	if d == nil {
		return nil
	}
	return d.State
}
