// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a95af6551377

package shared

// DirectoryServiceDeleteRequest is the request message for deleting a directory. It uses URL values for input.
type DirectoryServiceDeleteRequest struct {
}
