// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// DirectoryExpandMask - The fields to be included in the directory response.
type DirectoryExpandMask struct {
	// An array of fields to be included in the directory response.
	Paths []string `json:"paths,omitempty"`
}

func (d *DirectoryExpandMask) GetPaths() []string {
	if d == nil {
		return nil
	}
	return d.Paths
}
