// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EdgeServicePreviewEgressRulesUpdateRequest asks what saving a rule list
//
//	would do: whether Update accepts it, and how each host's verdict changes.
//	Nothing is saved.
type EdgeServicePreviewEgressRulesUpdateRequest struct {
	// Hosts to compare before and after, in the order results are returned.
	//  Empty runs only the save check.
	Hosts []string `json:"hosts,omitempty"`
	// The C1 user to evaluate as. Empty: rules naming a user or an entitlement
	//  report EDGE_EGRESS_PRINCIPAL_MATCH_UNKNOWN and never decide the verdict.
	PrincipalUserID *string             `json:"principalUserId,omitempty"`
	ProposedRules   *EdgeEgressRuleList `json:"proposedRules,omitempty"`
}

func (e *EdgeServicePreviewEgressRulesUpdateRequest) GetHosts() []string {
	if e == nil {
		return nil
	}
	return e.Hosts
}

func (e *EdgeServicePreviewEgressRulesUpdateRequest) GetPrincipalUserID() *string {
	if e == nil {
		return nil
	}
	return e.PrincipalUserID
}

func (e *EdgeServicePreviewEgressRulesUpdateRequest) GetProposedRules() *EdgeEgressRuleList {
	if e == nil {
		return nil
	}
	return e.ProposedRules
}
