// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The EdgeServiceListEgressTopAgentsResponse message.
type EdgeServiceListEgressTopAgentsResponse struct {
	// Ordered by call_count descending, limited to page_size. No pagination
	//  cursor -- this is a fixed top-N, not a full list.
	Agents []TBTopAgent `json:"agents,omitempty"`
}

func (e *EdgeServiceListEgressTopAgentsResponse) GetAgents() []TBTopAgent {
	if e == nil {
		return nil
	}
	return e.Agents
}
