// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EmailOTPConstraints configures one-time codes delivered by email.
type EmailOTPConstraints struct {
	// Number of digits in each code.
	CodeLength *int `json:"codeLength,omitempty"`
	// Number of incorrect attempts allowed before the code is invalidated.
	MaxAttempts *int `json:"maxAttempts,omitempty"`
	// How long a code remains valid, in seconds.
	TTLSeconds *int `json:"ttlSeconds,omitempty"`
}

func (e *EmailOTPConstraints) GetCodeLength() *int {
	if e == nil {
		return nil
	}
	return e.CodeLength
}

func (e *EmailOTPConstraints) GetMaxAttempts() *int {
	if e == nil {
		return nil
	}
	return e.MaxAttempts
}

func (e *EmailOTPConstraints) GetTTLSeconds() *int {
	if e == nil {
		return nil
	}
	return e.TTLSeconds
}
