// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The ExportServiceListEventsRequest message.
type ExportServiceListEventsRequest struct {
	// The pageSize field.
	PageSize *int `json:"pageSize,omitempty"`
	// The pageToken field.
	PageToken *string `json:"pageToken,omitempty"`
}

func (e *ExportServiceListEventsRequest) GetPageSize() *int {
	if e == nil {
		return nil
	}
	return e.PageSize
}

func (e *ExportServiceListEventsRequest) GetPageToken() *string {
	if e == nil {
		return nil
	}
	return e.PageToken
}
