// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 851451b3ba43

package shared

// The ExportServiceDeleteResponse message.
type ExportServiceDeleteResponse struct {
}
