// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ExporterInput - The Exporter message.
//
// This message contains a oneof named export_to. Only a single field of the following list may be set at a time:
//   - datasource
type ExporterInput struct {
	// The ExportToDatasource message.
	ExportToDatasource *ExportToDatasource `json:"datasource,omitempty"`
	// The displayName field.
	DisplayName *string `json:"displayName,omitempty"`
}

func (o *ExporterInput) GetExportToDatasource() *ExportToDatasource {
	if o == nil {
		return nil
	}
	return o.ExportToDatasource
}

func (o *ExporterInput) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}
