// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The FindingSearchResponse message.
type FindingSearchResponse struct {
	// The list field.
	List []Finding `json:"list,omitempty"`
	// The nextPageToken field.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

func (f *FindingSearchResponse) GetList() []Finding {
	if f == nil {
		return nil
	}
	return f.List
}

func (f *FindingSearchResponse) GetNextPageToken() *string {
	if f == nil {
		return nil
	}
	return f.NextPageToken
}
