// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 49420e7907e1

package shared

// ForceSyncRequest - Signal the connector to start syncing. This puts the sync on the queue. It does not guarantee immediate sync. Long syncs still take minutes to hours.
type ForceSyncRequest struct {
}
