// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The FunctionsServiceCreateFunctionResponse message.
type FunctionsServiceCreateFunctionResponse struct {
	// FunctionCommit represents a single commit in a function's history
	FunctionCommit *FunctionCommit `json:"commit,omitempty"`
	// Function represents a customer-provided code extension in the API
	Function *Function `json:"function,omitempty"`
}

func (f *FunctionsServiceCreateFunctionResponse) GetFunctionCommit() *FunctionCommit {
	if f == nil {
		return nil
	}
	return f.FunctionCommit
}

func (f *FunctionsServiceCreateFunctionResponse) GetFunction() *Function {
	if f == nil {
		return nil
	}
	return f.Function
}
