// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The FunctionsServiceUpdateFunctionResponse message.
type FunctionsServiceUpdateFunctionResponse struct {
	Commit   *FunctionCommit `json:"commit,omitempty"`
	Function *Function       `json:"function,omitempty"`
}

func (f *FunctionsServiceUpdateFunctionResponse) GetCommit() *FunctionCommit {
	if f == nil {
		return nil
	}
	return f.Commit
}

func (f *FunctionsServiceUpdateFunctionResponse) GetFunction() *Function {
	if f == nil {
		return nil
	}
	return f.Function
}
