// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The FundPolicyServiceListHistoryResponse message.
type FundPolicyServiceListHistoryResponse struct {
	// The list field.
	List []FundPolicyHistoryEntry `json:"list,omitempty"`
	// The nextPageToken field.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

func (f *FundPolicyServiceListHistoryResponse) GetList() []FundPolicyHistoryEntry {
	if f == nil {
		return nil
	}
	return f.List
}

func (f *FundPolicyServiceListHistoryResponse) GetNextPageToken() *string {
	if f == nil {
		return nil
	}
	return f.NextPageToken
}
