// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/internal/utils"
	"time"
)

// The GatewayKey message.
type GatewayKey struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// The displayName field.
	DisplayName *string `json:"displayName,omitempty"`
	// The id field.
	ID *string `json:"id,omitempty"`
	// The keyPrefix field.
	KeyPrefix *string    `json:"keyPrefix,omitempty"`
	RevokedAt *time.Time `json:"revokedAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

func (g GatewayKey) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GatewayKey) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GatewayKey) GetCreatedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.CreatedAt
}

func (g *GatewayKey) GetDisplayName() *string {
	if g == nil {
		return nil
	}
	return g.DisplayName
}

func (g *GatewayKey) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GatewayKey) GetKeyPrefix() *string {
	if g == nil {
		return nil
	}
	return g.KeyPrefix
}

func (g *GatewayKey) GetRevokedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.RevokedAt
}

func (g *GatewayKey) GetUpdatedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.UpdatedAt
}
