// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 647fbcd70f2b

package shared

// The GetUserNotificationSettingsResponse message.
type GetUserNotificationSettingsResponse struct {
	// UserNotificationSettings contains the calling user's personal notification preferences.
	UserNotificationSettings *UserNotificationSettings `json:"userNotificationSettings,omitempty"`
}

func (g *GetUserNotificationSettingsResponse) GetUserNotificationSettings() *UserNotificationSettings {
	if g == nil {
		return nil
	}
	return g.UserNotificationSettings
}
