// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The ListOwnedServiceAccountsRequest message.
type ListOwnedServiceAccountsRequest struct {
	ExpandMask *AppUserExpandMask `json:"expandMask,omitempty"`
	// The maximum number of results to return per page.
	PageSize *int `json:"pageSize,omitempty"`
	// The token for fetching the next page of results.
	PageToken *string `json:"pageToken,omitempty"`
}

func (l *ListOwnedServiceAccountsRequest) GetExpandMask() *AppUserExpandMask {
	if l == nil {
		return nil
	}
	return l.ExpandMask
}

func (l *ListOwnedServiceAccountsRequest) GetPageSize() *int {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListOwnedServiceAccountsRequest) GetPageToken() *string {
	if l == nil {
		return nil
	}
	return l.PageToken
}
