// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MCPResourceServiceSearchResponse returns matching MCP resources.
type MCPResourceServiceSearchResponse struct {
	// Matching MCP resources.
	List []MCPResource `json:"list,omitempty"`
	// Token for next page.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

func (m *MCPResourceServiceSearchResponse) GetList() []MCPResource {
	if m == nil {
		return nil
	}
	return m.List
}

func (m *MCPResourceServiceSearchResponse) GetNextPageToken() *string {
	if m == nil {
		return nil
	}
	return m.NextPageToken
}
