// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MCPServerServiceUpdateResponse returns the updated MCP server.
type MCPServerServiceUpdateResponse struct {
	McpServer *MCPServerView `json:"mcpServer,omitempty"`
}

func (m *MCPServerServiceUpdateResponse) GetMcpServer() *MCPServerView {
	if m == nil {
		return nil
	}
	return m.McpServer
}
