// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MCPToolServiceGetResponse returns a single MCP tool.
type MCPToolServiceGetResponse struct {
	Tool *MCPTool `json:"tool,omitempty"`
}

func (m *MCPToolServiceGetResponse) GetTool() *MCPTool {
	if m == nil {
		return nil
	}
	return m.Tool
}
