// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The MyFundLimitsServicePauseResponse message.
type MyFundLimitsServicePauseResponse struct {
	Limit *MyFundLimit `json:"limit,omitempty"`
}

func (m *MyFundLimitsServicePauseResponse) GetLimit() *MyFundLimit {
	if m == nil {
		return nil
	}
	return m.Limit
}
