// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The NotificationConfig message.
type NotificationConfig struct {
	// The sendClose field.
	SendClose *bool `json:"sendClose,omitempty"`
	// The sendReminders field.
	SendReminders *bool `json:"sendReminders,omitempty"`
}

func (n *NotificationConfig) GetSendClose() *bool {
	if n == nil {
		return nil
	}
	return n.SendClose
}

func (n *NotificationConfig) GetSendReminders() *bool {
	if n == nil {
		return nil
	}
	return n.SendReminders
}
