// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The PaperSecretAdminServiceGetResponse message.
type PaperSecretAdminServiceGetResponse struct {
	// PaperSecret is the API view of a secret (combines Vault + PaperVault fields).
	//  The vault_id is the primary identifier (Vault.id).
	PaperSecret *PaperSecret `json:"secret,omitempty"`
	// The shareUrl field.
	ShareURL *string `json:"shareUrl,omitempty"`
}

func (p *PaperSecretAdminServiceGetResponse) GetPaperSecret() *PaperSecret {
	if p == nil {
		return nil
	}
	return p.PaperSecret
}

func (p *PaperSecretAdminServiceGetResponse) GetShareURL() *string {
	if p == nil {
		return nil
	}
	return p.ShareURL
}
