// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/internal/utils"
	"time"
)

// PersonalDeviceClient is a single app client on a device. The client
//
//	authenticates with its own asymmetric key; there is no client secret.
type PersonalDeviceClient struct {
	// The full client_id of the device credential.
	ClientID *string `json:"clientId,omitempty"`
	// The human-friendly client name from its registration metadata.
	ClientName *string `json:"clientName,omitempty"`
	// The stable identity of this client's per-app key.
	ConsumerKeyID *string    `json:"consumerKeyId,omitempty"`
	CreatedAt     *time.Time `json:"createdAt,omitempty"`
	// The device operating system captured for this client, e.g. "macos-14.5".
	DeviceOs *string `json:"deviceOs,omitempty"`
	// The device surface captured for this client, e.g. "macos-desktop".
	DeviceSurface *string `json:"deviceSurface,omitempty"`
	// The display name of the device credential.
	DisplayName *string `json:"displayName,omitempty"`
	// The unique ID of the device client (the local part of client_id).
	ID         *string    `json:"id,omitempty"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	// An identifier for the client software, from its registration metadata.
	SoftwareID *string `json:"softwareId,omitempty"`
	// The version of the client software, from its registration metadata.
	SoftwareVersion *string `json:"softwareVersion,omitempty"`
}

func (p PersonalDeviceClient) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PersonalDeviceClient) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PersonalDeviceClient) GetClientID() *string {
	if p == nil {
		return nil
	}
	return p.ClientID
}

func (p *PersonalDeviceClient) GetClientName() *string {
	if p == nil {
		return nil
	}
	return p.ClientName
}

func (p *PersonalDeviceClient) GetConsumerKeyID() *string {
	if p == nil {
		return nil
	}
	return p.ConsumerKeyID
}

func (p *PersonalDeviceClient) GetCreatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PersonalDeviceClient) GetDeviceOs() *string {
	if p == nil {
		return nil
	}
	return p.DeviceOs
}

func (p *PersonalDeviceClient) GetDeviceSurface() *string {
	if p == nil {
		return nil
	}
	return p.DeviceSurface
}

func (p *PersonalDeviceClient) GetDisplayName() *string {
	if p == nil {
		return nil
	}
	return p.DisplayName
}

func (p *PersonalDeviceClient) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PersonalDeviceClient) GetLastUsedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.LastUsedAt
}

func (p *PersonalDeviceClient) GetSoftwareID() *string {
	if p == nil {
		return nil
	}
	return p.SoftwareID
}

func (p *PersonalDeviceClient) GetSoftwareVersion() *string {
	if p == nil {
		return nil
	}
	return p.SoftwareVersion
}
