// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// PolicyEditorValidateResponse - The EditorValidateResponse message.
type PolicyEditorValidateResponse struct {
	// The markers field.
	Markers []EditorMarker `json:"markers,omitempty"`
}

func (p *PolicyEditorValidateResponse) GetMarkers() []EditorMarker {
	if p == nil {
		return nil
	}
	return p.Markers
}
