// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RemoveAppOwnerRequest is the request body for removing an app owner. It uses URL values for input.
type RemoveAppOwnerRequest struct {
}
