// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f8f8adb09a6b

package shared

// RemoveAppEntitlementOwnerResponse - The empty response message for removing an app entitlement owner.
type RemoveAppEntitlementOwnerResponse struct {
}
