// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a90a851204ea

package shared

// RemoveAutomationExclusionResponse - Empty response with a status code indicating success.
type RemoveAutomationExclusionResponse struct {
}
