// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/internal/utils"
	"time"
)

type Lineage struct {
}

type ReportRunParameterValues struct {
}

// ReportRunStatus - The status field.
type ReportRunStatus string

const (
	ReportRunStatusReportRunStatusUnspecified  ReportRunStatus = "REPORT_RUN_STATUS_UNSPECIFIED"
	ReportRunStatusReportRunStatusPending      ReportRunStatus = "REPORT_RUN_STATUS_PENDING"
	ReportRunStatusReportRunStatusSucceeded    ReportRunStatus = "REPORT_RUN_STATUS_SUCCEEDED"
	ReportRunStatusReportRunStatusFailed       ReportRunStatus = "REPORT_RUN_STATUS_FAILED"
	ReportRunStatusReportRunStatusStaleProgram ReportRunStatus = "REPORT_RUN_STATUS_STALE_PROGRAM"
)

func (e ReportRunStatus) ToPointer() *ReportRunStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ReportRunStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "REPORT_RUN_STATUS_UNSPECIFIED", "REPORT_RUN_STATUS_PENDING", "REPORT_RUN_STATUS_SUCCEEDED", "REPORT_RUN_STATUS_FAILED", "REPORT_RUN_STATUS_STALE_PROGRAM":
			return true
		}
	}
	return false
}

// ReportRun is one execution of a Report's program. Write-once.
type ReportRun struct {
	// The artifactUrl field.
	ArtifactURL *string `json:"artifactUrl,omitempty"`
	// Where the output came from, kept for provenance rather than to read it back:
	//  the surface itself is in surface_snapshot. Both are required to address a
	//  surface, and a headless refresh has neither.
	ConversationID *string    `json:"conversationId,omitempty"`
	CreatedAt      *time.Time `json:"createdAt,omitempty"`
	DeletedAt      *time.Time `json:"deletedAt,omitempty"`
	// The error field.
	Error     *string    `json:"error,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	// KSUID, so runs sort by time.
	ID *string `json:"id,omitempty"`
	// Not a live join: the originating code-mode invocation is archived at the
	//  code-mode retention cutoff.
	InvocationID    *string                   `json:"invocationId,omitempty"`
	Lineage         *Lineage                  `json:"lineage,omitempty"`
	ParameterValues *ReportRunParameterValues `json:"parameterValues,omitempty"`
	Program         *ProgramRef               `json:"program,omitempty"`
	// The reportId field.
	ReportID *string `json:"reportId,omitempty"`
	// Copied from the invocation's user_id, which is archived at the code-mode
	//  retention cutoff. Not Report.created_by_user_id — a refresh may execute as a
	//  different principal than the report's owner.
	RunByUserID *string `json:"runByUserId,omitempty"`
	// Never written: for a run saved out of a conversation, provenance is read back
	//  through A2UIService.GetSurfaceProvenance, which reads the surface's own
	//  components. A headless refresh has no conversation or surface to ask about,
	//  and how such a run reports what it read is still open.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Sources []ReportSource `json:"sources,omitempty"`
	// The status field.
	Status *ReportRunStatus `json:"status,omitempty"`
	// The surfaceId field.
	SurfaceID       *string      `json:"surfaceId,omitempty"`
	SurfaceSnapshot *A2UISurface `json:"surfaceSnapshot,omitempty"`
	// The tenantId field.
	TenantID  *string    `json:"tenantId,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// The vfsId field.
	VfsID *string `json:"vfsId,omitempty"`
}

func (r ReportRun) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReportRun) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReportRun) GetArtifactURL() *string {
	if r == nil {
		return nil
	}
	return r.ArtifactURL
}

func (r *ReportRun) GetConversationID() *string {
	if r == nil {
		return nil
	}
	return r.ConversationID
}

func (r *ReportRun) GetCreatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *ReportRun) GetDeletedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.DeletedAt
}

func (r *ReportRun) GetError() *string {
	if r == nil {
		return nil
	}
	return r.Error
}

func (r *ReportRun) GetExpiresAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.ExpiresAt
}

func (r *ReportRun) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *ReportRun) GetInvocationID() *string {
	if r == nil {
		return nil
	}
	return r.InvocationID
}

func (r *ReportRun) GetLineage() *Lineage {
	if r == nil {
		return nil
	}
	return r.Lineage
}

func (r *ReportRun) GetParameterValues() *ReportRunParameterValues {
	if r == nil {
		return nil
	}
	return r.ParameterValues
}

func (r *ReportRun) GetProgram() *ProgramRef {
	if r == nil {
		return nil
	}
	return r.Program
}

func (r *ReportRun) GetReportID() *string {
	if r == nil {
		return nil
	}
	return r.ReportID
}

func (r *ReportRun) GetRunByUserID() *string {
	if r == nil {
		return nil
	}
	return r.RunByUserID
}

func (r *ReportRun) GetSources() []ReportSource {
	if r == nil {
		return nil
	}
	return r.Sources
}

func (r *ReportRun) GetStatus() *ReportRunStatus {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *ReportRun) GetSurfaceID() *string {
	if r == nil {
		return nil
	}
	return r.SurfaceID
}

func (r *ReportRun) GetSurfaceSnapshot() *A2UISurface {
	if r == nil {
		return nil
	}
	return r.SurfaceSnapshot
}

func (r *ReportRun) GetTenantID() *string {
	if r == nil {
		return nil
	}
	return r.TenantID
}

func (r *ReportRun) GetUpdatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.UpdatedAt
}

func (r *ReportRun) GetVfsID() *string {
	if r == nil {
		return nil
	}
	return r.VfsID
}
