// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The RequestCreatedPreference message.
type RequestCreatedPreference struct {
	// The enabled field.
	Enabled *bool `json:"enabled,omitempty"`
	// The locked field.
	Locked *bool `json:"locked,omitempty"`
}

func (r *RequestCreatedPreference) GetEnabled() *bool {
	if r == nil {
		return nil
	}
	return r.Enabled
}

func (r *RequestCreatedPreference) GetLocked() *bool {
	if r == nil {
		return nil
	}
	return r.Locked
}
