// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The RequestCatalogManagementServiceUpdateAppEntitlementsRequest object is used to update app entitlements to a request catalog id.
type RequestCatalogManagementServiceUpdateAppEntitlementsRequest struct {
	// The entitlement to get from the request catalog.
	AppEntitlements []AppEntitlementRef `json:"appEntitlements"`
}

func (o *RequestCatalogManagementServiceUpdateAppEntitlementsRequest) GetAppEntitlements() []AppEntitlementRef {
	if o == nil {
		return nil
	}
	return o.AppEntitlements
}
