// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// RequestCatalogManagementServiceDeleteRequestableEntryRequest - Delete a single requestable entry
type RequestCatalogManagementServiceDeleteRequestableEntryRequest struct {
}
