// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CurrentType - Current stored type. UNSPECIFIED means the profile predates type backfill
//
//	or contains an unknown future value.
type CurrentType string

const (
	CurrentTypeRequestCatalogTypeUnspecified      CurrentType = "REQUEST_CATALOG_TYPE_UNSPECIFIED"
	CurrentTypeRequestCatalogTypeCatalog          CurrentType = "REQUEST_CATALOG_TYPE_CATALOG"
	CurrentTypeRequestCatalogTypeProfile          CurrentType = "REQUEST_CATALOG_TYPE_PROFILE"
	CurrentTypeRequestCatalogTypeCatalogAndBundle CurrentType = "REQUEST_CATALOG_TYPE_CATALOG_AND_BUNDLE"
	CurrentTypeRequestCatalogTypeBundle           CurrentType = "REQUEST_CATALOG_TYPE_BUNDLE"
)

func (e CurrentType) ToPointer() *CurrentType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CurrentType) IsExact() bool {
	if e != nil {
		switch *e {
		case "REQUEST_CATALOG_TYPE_UNSPECIFIED", "REQUEST_CATALOG_TYPE_CATALOG", "REQUEST_CATALOG_TYPE_PROFILE", "REQUEST_CATALOG_TYPE_CATALOG_AND_BUNDLE", "REQUEST_CATALOG_TYPE_BUNDLE":
			return true
		}
	}
	return false
}

// RequestCatalogManagementServicePlanTypeChangeResponseTargetType - Type requested by the caller.
type RequestCatalogManagementServicePlanTypeChangeResponseTargetType string

const (
	RequestCatalogManagementServicePlanTypeChangeResponseTargetTypeRequestCatalogTypeUnspecified      RequestCatalogManagementServicePlanTypeChangeResponseTargetType = "REQUEST_CATALOG_TYPE_UNSPECIFIED"
	RequestCatalogManagementServicePlanTypeChangeResponseTargetTypeRequestCatalogTypeCatalog          RequestCatalogManagementServicePlanTypeChangeResponseTargetType = "REQUEST_CATALOG_TYPE_CATALOG"
	RequestCatalogManagementServicePlanTypeChangeResponseTargetTypeRequestCatalogTypeProfile          RequestCatalogManagementServicePlanTypeChangeResponseTargetType = "REQUEST_CATALOG_TYPE_PROFILE"
	RequestCatalogManagementServicePlanTypeChangeResponseTargetTypeRequestCatalogTypeCatalogAndBundle RequestCatalogManagementServicePlanTypeChangeResponseTargetType = "REQUEST_CATALOG_TYPE_CATALOG_AND_BUNDLE"
	RequestCatalogManagementServicePlanTypeChangeResponseTargetTypeRequestCatalogTypeBundle           RequestCatalogManagementServicePlanTypeChangeResponseTargetType = "REQUEST_CATALOG_TYPE_BUNDLE"
)

func (e RequestCatalogManagementServicePlanTypeChangeResponseTargetType) ToPointer() *RequestCatalogManagementServicePlanTypeChangeResponseTargetType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RequestCatalogManagementServicePlanTypeChangeResponseTargetType) IsExact() bool {
	if e != nil {
		switch *e {
		case "REQUEST_CATALOG_TYPE_UNSPECIFIED", "REQUEST_CATALOG_TYPE_CATALOG", "REQUEST_CATALOG_TYPE_PROFILE", "REQUEST_CATALOG_TYPE_CATALOG_AND_BUNDLE", "REQUEST_CATALOG_TYPE_BUNDLE":
			return true
		}
	}
	return false
}

// RequestCatalogManagementServicePlanTypeChangeResponse - Describes behavior affected by an access profile type change.
type RequestCatalogManagementServicePlanTypeChangeResponse struct {
	// Current stored type. UNSPECIFIED means the profile predates type backfill
	//  or contains an unknown future value.
	CurrentType *CurrentType `json:"currentType,omitempty"`
	// Deterministically ordered behavior affected by the transition. These
	//  impacts describe what the target type does not support; the change does not
	//  remove or modify the underlying state.
	Impacts []RequestCatalogTypeChangeImpact `json:"impacts,omitempty"`
	// Type requested by the caller.
	TargetType *RequestCatalogManagementServicePlanTypeChangeResponseTargetType `json:"targetType,omitempty"`
}

func (r *RequestCatalogManagementServicePlanTypeChangeResponse) GetCurrentType() *CurrentType {
	if r == nil {
		return nil
	}
	return r.CurrentType
}

func (r *RequestCatalogManagementServicePlanTypeChangeResponse) GetImpacts() []RequestCatalogTypeChangeImpact {
	if r == nil {
		return nil
	}
	return r.Impacts
}

func (r *RequestCatalogManagementServicePlanTypeChangeResponse) GetTargetType() *RequestCatalogManagementServicePlanTypeChangeResponseTargetType {
	if r == nil {
		return nil
	}
	return r.TargetType
}
