// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The ResponseProvisionStepErrored message.
type ResponseProvisionStepErrored struct {
	// optional comment
	Comment *string `json:"comment,omitempty"`
}

func (o *ResponseProvisionStepErrored) GetComment() *string {
	if o == nil {
		return nil
	}
	return o.Comment
}
