// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/conductorone/terraform-provider-conductorone/v2/internal/sdk/internal/utils"
	"time"
)

// RoleMiningManagementRunStatus - The status field.
type RoleMiningManagementRunStatus string

const (
	RoleMiningManagementRunStatusRunStatusUnspecified RoleMiningManagementRunStatus = "RUN_STATUS_UNSPECIFIED"
	RoleMiningManagementRunStatusRunStatusRunning     RoleMiningManagementRunStatus = "RUN_STATUS_RUNNING"
	RoleMiningManagementRunStatusRunStatusCompleted   RoleMiningManagementRunStatus = "RUN_STATUS_COMPLETED"
	RoleMiningManagementRunStatusRunStatusFailed      RoleMiningManagementRunStatus = "RUN_STATUS_FAILED"
)

func (e RoleMiningManagementRunStatus) ToPointer() *RoleMiningManagementRunStatus {
	return &e
}
func (e *RoleMiningManagementRunStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "RUN_STATUS_UNSPECIFIED":
		fallthrough
	case "RUN_STATUS_RUNNING":
		fallthrough
	case "RUN_STATUS_COMPLETED":
		fallthrough
	case "RUN_STATUS_FAILED":
		*e = RoleMiningManagementRunStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RoleMiningManagementRunStatus: %v", v)
	}
}

// TriggerType - The triggerType field.
type TriggerType string

const (
	TriggerTypeTriggerTypeUnspecified      TriggerType = "TRIGGER_TYPE_UNSPECIFIED"
	TriggerTypeTriggerTypeManual           TriggerType = "TRIGGER_TYPE_MANUAL"
	TriggerTypeTriggerTypeUpliftCompletion TriggerType = "TRIGGER_TYPE_UPLIFT_COMPLETION"
	TriggerTypeTriggerTypeScheduled        TriggerType = "TRIGGER_TYPE_SCHEDULED"
)

func (e TriggerType) ToPointer() *TriggerType {
	return &e
}
func (e *TriggerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TRIGGER_TYPE_UNSPECIFIED":
		fallthrough
	case "TRIGGER_TYPE_MANUAL":
		fallthrough
	case "TRIGGER_TYPE_UPLIFT_COMPLETION":
		fallthrough
	case "TRIGGER_TYPE_SCHEDULED":
		*e = TriggerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TriggerType: %v", v)
	}
}

// The RoleMiningManagementRun message.
type RoleMiningManagementRun struct {
	// The cohortsAnalyzed field.
	CohortsAnalyzed *int       `json:"cohortsAnalyzed,omitempty"`
	CompletedAt     *time.Time `json:"completedAt,omitempty"`
	CreatedAt       *time.Time `json:"createdAt,omitempty"`
	// The errorMessage field.
	ErrorMessage *string `json:"errorMessage,omitempty"`
	// The id field.
	ID *string `json:"id,omitempty"`
	// The status field.
	Status *RoleMiningManagementRunStatus `json:"status,omitempty"`
	// The suggestionsGenerated field.
	SuggestionsGenerated *int `json:"suggestionsGenerated,omitempty"`
	// The totalUsers field.
	TotalUsers *int `json:"totalUsers,omitempty"`
	// The triggerDetail field.
	TriggerDetail *string `json:"triggerDetail,omitempty"`
	// The triggerType field.
	TriggerType *TriggerType `json:"triggerType,omitempty"`
	UpdatedAt   *time.Time   `json:"updatedAt,omitempty"`
}

func (r RoleMiningManagementRun) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RoleMiningManagementRun) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RoleMiningManagementRun) GetCohortsAnalyzed() *int {
	if r == nil {
		return nil
	}
	return r.CohortsAnalyzed
}

func (r *RoleMiningManagementRun) GetCompletedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CompletedAt
}

func (r *RoleMiningManagementRun) GetCreatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *RoleMiningManagementRun) GetErrorMessage() *string {
	if r == nil {
		return nil
	}
	return r.ErrorMessage
}

func (r *RoleMiningManagementRun) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RoleMiningManagementRun) GetStatus() *RoleMiningManagementRunStatus {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *RoleMiningManagementRun) GetSuggestionsGenerated() *int {
	if r == nil {
		return nil
	}
	return r.SuggestionsGenerated
}

func (r *RoleMiningManagementRun) GetTotalUsers() *int {
	if r == nil {
		return nil
	}
	return r.TotalUsers
}

func (r *RoleMiningManagementRun) GetTriggerDetail() *string {
	if r == nil {
		return nil
	}
	return r.TriggerDetail
}

func (r *RoleMiningManagementRun) GetTriggerType() *TriggerType {
	if r == nil {
		return nil
	}
	return r.TriggerType
}

func (r *RoleMiningManagementRun) GetUpdatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.UpdatedAt
}
