// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/internal/utils"
	"time"
)

// SearchMySpendUsageRequest selects a half-open finalization-time interval.
//
//	The caller's identity is always obtained from the authenticated session.
//	Bounds must have microsecond precision; finer timestamps are rejected.
type SearchMySpendUsageRequest struct {
	// Optional application filter; does not grant access to another user's calls.
	AppID   *string    `json:"appId,omitempty"`
	EndTime *time.Time `json:"endTime,omitempty"`
	// Maximum rows per page. Zero uses the server default.
	PageSize *int `json:"pageSize,omitempty"`
	// Opaque position token from a previous response. Keep history selectors
	//  unchanged when continuing; concurrent writes may shift page boundaries.
	//  Caller authorization is applied independently on every request.
	PageToken *string    `json:"pageToken,omitempty"`
	StartTime *time.Time `json:"startTime,omitempty"`
}

func (s SearchMySpendUsageRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchMySpendUsageRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SearchMySpendUsageRequest) GetAppID() *string {
	if s == nil {
		return nil
	}
	return s.AppID
}

func (s *SearchMySpendUsageRequest) GetEndTime() *time.Time {
	if s == nil {
		return nil
	}
	return s.EndTime
}

func (s *SearchMySpendUsageRequest) GetPageSize() *int {
	if s == nil {
		return nil
	}
	return s.PageSize
}

func (s *SearchMySpendUsageRequest) GetPageToken() *string {
	if s == nil {
		return nil
	}
	return s.PageToken
}

func (s *SearchMySpendUsageRequest) GetStartTime() *time.Time {
	if s == nil {
		return nil
	}
	return s.StartTime
}
