// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SearchStepUpProvidersRequestProviderType - The providerType field.
type SearchStepUpProvidersRequestProviderType string

const (
	SearchStepUpProvidersRequestProviderTypeProviderTypeUnspecified SearchStepUpProvidersRequestProviderType = "PROVIDER_TYPE_UNSPECIFIED"
	SearchStepUpProvidersRequestProviderTypeProviderTypeOauth2      SearchStepUpProvidersRequestProviderType = "PROVIDER_TYPE_OAUTH2"
	SearchStepUpProvidersRequestProviderTypeProviderTypeMicrosoft   SearchStepUpProvidersRequestProviderType = "PROVIDER_TYPE_MICROSOFT"
)

func (e SearchStepUpProvidersRequestProviderType) ToPointer() *SearchStepUpProvidersRequestProviderType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SearchStepUpProvidersRequestProviderType) IsExact() bool {
	if e != nil {
		switch *e {
		case "PROVIDER_TYPE_UNSPECIFIED", "PROVIDER_TYPE_OAUTH2", "PROVIDER_TYPE_MICROSOFT":
			return true
		}
	}
	return false
}

// SearchStepUpProvidersRequest - Request message for searching step-up providers
type SearchStepUpProvidersRequest struct {
	// Maximum number of results to return
	PageSize *int `json:"pageSize,omitempty"`
	// Token for pagination
	PageToken *string `json:"pageToken,omitempty"`
	// The providerType field.
	ProviderType *SearchStepUpProvidersRequestProviderType `json:"providerType,omitempty"`
	// Filter by name (partial match)
	Query *string `json:"query,omitempty"`
	// Filter to specific providers by their references.
	Refs []StepUpProviderRef `json:"refs,omitempty"`
}

func (s *SearchStepUpProvidersRequest) GetPageSize() *int {
	if s == nil {
		return nil
	}
	return s.PageSize
}

func (s *SearchStepUpProvidersRequest) GetPageToken() *string {
	if s == nil {
		return nil
	}
	return s.PageToken
}

func (s *SearchStepUpProvidersRequest) GetProviderType() *SearchStepUpProvidersRequestProviderType {
	if s == nil {
		return nil
	}
	return s.ProviderType
}

func (s *SearchStepUpProvidersRequest) GetQuery() *string {
	if s == nil {
		return nil
	}
	return s.Query
}

func (s *SearchStepUpProvidersRequest) GetRefs() []StepUpProviderRef {
	if s == nil {
		return nil
	}
	return s.Refs
}
