// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The ServicePrincipalServiceDeleteBindingRequest message.
type ServicePrincipalServiceDeleteBindingRequest struct {
	// The servicePrincipalId field.
	ServicePrincipalID *string                         `json:"servicePrincipalId,omitempty"`
	Subject            *ServicePrincipalBindingSubject `json:"subject,omitempty"`
}

func (s *ServicePrincipalServiceDeleteBindingRequest) GetServicePrincipalID() *string {
	if s == nil {
		return nil
	}
	return s.ServicePrincipalID
}

func (s *ServicePrincipalServiceDeleteBindingRequest) GetSubject() *ServicePrincipalBindingSubject {
	if s == nil {
		return nil
	}
	return s.Subject
}
