// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SessionPolicyPolicyOutcome - PolicyOutcome is the effect of a matched rule. Exactly one kind is set. For
//
//	session continuous-evaluation, the meaningful kinds are Allow (continue),
//	Deny (terminate), and StepUpRequired.
//
// This message contains a oneof named kind. Only a single field of the following list may be set at a time:
//   - allow
//   - deny
//   - stepUpRequired
//   - challengeRequired
//   - enrollmentRequired
type SessionPolicyPolicyOutcome struct {
	// Allow continues the session.
	SessionPolicyAllow *SessionPolicyAllow `json:"allow,omitempty"`
	// ChallengeRequired asks for an additional factor.
	SessionPolicyChallengeRequired *SessionPolicyChallengeRequired `json:"challengeRequired,omitempty"`
	// Deny terminates the session.
	SessionPolicyDeny *SessionPolicyDeny `json:"deny,omitempty"`
	// EnrollmentRequired tells the user to enroll a credential before continuing.
	SessionPolicyEnrollmentRequired *SessionPolicyEnrollmentRequired `json:"enrollmentRequired,omitempty"`
	// StepUpRequired demands a stronger re-authentication before the session may
	//  continue.
	SessionPolicyStepUpRequired *SessionPolicyStepUpRequired `json:"stepUpRequired,omitempty"`
}

func (s *SessionPolicyPolicyOutcome) GetSessionPolicyAllow() *SessionPolicyAllow {
	if s == nil {
		return nil
	}
	return s.SessionPolicyAllow
}

func (s *SessionPolicyPolicyOutcome) GetSessionPolicyChallengeRequired() *SessionPolicyChallengeRequired {
	if s == nil {
		return nil
	}
	return s.SessionPolicyChallengeRequired
}

func (s *SessionPolicyPolicyOutcome) GetSessionPolicyDeny() *SessionPolicyDeny {
	if s == nil {
		return nil
	}
	return s.SessionPolicyDeny
}

func (s *SessionPolicyPolicyOutcome) GetSessionPolicyEnrollmentRequired() *SessionPolicyEnrollmentRequired {
	if s == nil {
		return nil
	}
	return s.SessionPolicyEnrollmentRequired
}

func (s *SessionPolicyPolicyOutcome) GetSessionPolicyStepUpRequired() *SessionPolicyStepUpRequired {
	if s == nil {
		return nil
	}
	return s.SessionPolicyStepUpRequired
}
