// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The SessionPolicyServiceAssignGroupRequest message.
type SessionPolicyServiceAssignGroupRequest struct {
	// The group's app-entitlement ID. Every member of the group becomes assigned.
	GroupAppEntitlementID string `json:"groupAppEntitlementId"`
}

func (s *SessionPolicyServiceAssignGroupRequest) GetGroupAppEntitlementID() string {
	if s == nil {
		return ""
	}
	return s.GroupAppEntitlementID
}
