// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The SessionPolicyServiceUpdateResponse message.
type SessionPolicyServiceUpdateResponse struct {
	SessionPolicy *SessionPolicy `json:"sessionPolicy,omitempty"`
}

func (s *SessionPolicyServiceUpdateResponse) GetSessionPolicy() *SessionPolicy {
	if s == nil {
		return nil
	}
	return s.SessionPolicy
}
