// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The SessionPolicyServiceSearchRequest message.
type SessionPolicyServiceSearchRequest struct {
	// The pageSize field.
	PageSize *int `json:"pageSize,omitempty"`
	// The pageToken field.
	PageToken *string `json:"pageToken,omitempty"`
	// Free-text search over the policy name. Empty matches all policies.
	Query *string `json:"query,omitempty"`
	// Restrict results to these specific policies. Empty matches all policies.
	Refs []SessionPolicyRef `json:"refs,omitempty"`
}

func (s *SessionPolicyServiceSearchRequest) GetPageSize() *int {
	if s == nil {
		return nil
	}
	return s.PageSize
}

func (s *SessionPolicyServiceSearchRequest) GetPageToken() *string {
	if s == nil {
		return nil
	}
	return s.PageToken
}

func (s *SessionPolicyServiceSearchRequest) GetQuery() *string {
	if s == nil {
		return nil
	}
	return s.Query
}

func (s *SessionPolicyServiceSearchRequest) GetRefs() []SessionPolicyRef {
	if s == nil {
		return nil
	}
	return s.Refs
}
