// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7d0e67c3e53a

package shared

// SetAppOwnersResponseV2 - SetAppOwnersResponse is the empty response for setting app owners.
type SetAppOwnersResponseV2 struct {
}

// #region class-body-setappownersresponsev2
// #endregion class-body-setappownersresponsev2
