// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SetBundleAutomationRequest - The request message for creating or updating a bundle automation rule on a catalog.
//
// This message contains a oneof named conditions. Only a single field of the following list may be set at a time:
//   - entitlements
//   - cel
type SetBundleAutomationRequest struct {
	// The BundleAutomationRuleCEL message.
	BundleAutomationRuleCEL *BundleAutomationRuleCEL `json:"cel,omitempty"`
	// Whether to create access request tasks for matched users instead of granting directly.
	CreateTasks *bool `json:"createTasks,omitempty"`
	// Whether to disable the circuit breaker that pauses the automation when excessive membership changes are detected.
	DisableCircuitBreaker *bool `json:"disableCircuitBreaker,omitempty"`
	// Whether the automation should actively run on its schedule.
	Enabled *bool `json:"enabled,omitempty"`
	// The BundleAutomationRuleEntitlement message.
	BundleAutomationRuleEntitlement *BundleAutomationRuleEntitlement `json:"entitlements,omitempty"`
}

func (s *SetBundleAutomationRequest) GetBundleAutomationRuleCEL() *BundleAutomationRuleCEL {
	if s == nil {
		return nil
	}
	return s.BundleAutomationRuleCEL
}

func (s *SetBundleAutomationRequest) GetCreateTasks() *bool {
	if s == nil {
		return nil
	}
	return s.CreateTasks
}

func (s *SetBundleAutomationRequest) GetDisableCircuitBreaker() *bool {
	if s == nil {
		return nil
	}
	return s.DisableCircuitBreaker
}

func (s *SetBundleAutomationRequest) GetEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.Enabled
}

func (s *SetBundleAutomationRequest) GetBundleAutomationRuleEntitlement() *BundleAutomationRuleEntitlement {
	if s == nil {
		return nil
	}
	return s.BundleAutomationRuleEntitlement
}
