// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The SignInPolicyServiceGetResponse message.
type SignInPolicyServiceGetResponse struct {
	SignInPolicy *SignInPolicy `json:"signInPolicy,omitempty"`
}

func (s *SignInPolicyServiceGetResponse) GetSignInPolicy() *SignInPolicy {
	if s == nil {
		return nil
	}
	return s.SignInPolicy
}
