// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SSFReceiverStreamServiceDeleteResponse is empty on success.
type SSFReceiverStreamServiceDeleteResponse struct {
}
