// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SSOApplicationServiceListResponse returns a page of SSO applications.
type SSOApplicationServiceListResponse struct {
	// The page of SSO applications.
	List []SSOApplication `json:"list,omitempty"`
	// Pagination token for the next page, or empty if there are no more results.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

func (s *SSOApplicationServiceListResponse) GetList() []SSOApplication {
	if s == nil {
		return nil
	}
	return s.List
}

func (s *SSOApplicationServiceListResponse) GetNextPageToken() *string {
	if s == nil {
		return nil
	}
	return s.NextPageToken
}
