// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The SubjectAppLimitServiceSetLimitResponse message.
type SubjectAppLimitServiceSetLimitResponse struct {
	Limit *SubjectAppLimit `json:"limit,omitempty"`
}

func (s *SubjectAppLimitServiceSetLimitResponse) GetLimit() *SubjectAppLimit {
	if s == nil {
		return nil
	}
	return s.Limit
}
