// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The TaskAuditWebhookApprovalAttempt message.
type TaskAuditWebhookApprovalAttempt struct {
	// The webhookId field.
	WebhookID *string `json:"webhookId,omitempty"`
	// The webhookInstanceId field.
	WebhookInstanceID *string `json:"webhookInstanceId,omitempty"`
	// The webhookName field.
	WebhookName *string `json:"webhookName,omitempty"`
	// The webhookUrl field.
	WebhookURL *string `json:"webhookUrl,omitempty"`
}

func (t *TaskAuditWebhookApprovalAttempt) GetWebhookID() *string {
	if t == nil {
		return nil
	}
	return t.WebhookID
}

func (t *TaskAuditWebhookApprovalAttempt) GetWebhookInstanceID() *string {
	if t == nil {
		return nil
	}
	return t.WebhookInstanceID
}

func (t *TaskAuditWebhookApprovalAttempt) GetWebhookName() *string {
	if t == nil {
		return nil
	}
	return t.WebhookName
}

func (t *TaskAuditWebhookApprovalAttempt) GetWebhookURL() *string {
	if t == nil {
		return nil
	}
	return t.WebhookURL
}
