// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// TaskActionsServiceCloseResponseExpanded - Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
type TaskActionsServiceCloseResponseExpanded struct {
}

// The TaskActionsServiceCloseResponse returns a task view with paths indicating the location of expanded items in the array.
type TaskActionsServiceCloseResponse struct {
	// List of serialized related objects.
	Expanded []TaskActionsServiceCloseResponseExpanded `json:"expanded,omitempty"`
	// The ID of the task close action created by this request.
	TaskActionID *string `json:"taskActionId,omitempty"`
	// Contains a task and JSONPATH expressions that describe where in the expanded array related objects are located. This view can be used to display a fully-detailed dashboard of task information.
	TaskView *TaskView `json:"taskView,omitempty"`
}

func (t *TaskActionsServiceCloseResponse) GetExpanded() []TaskActionsServiceCloseResponseExpanded {
	if t == nil {
		return nil
	}
	return t.Expanded
}

func (t *TaskActionsServiceCloseResponse) GetTaskActionID() *string {
	if t == nil {
		return nil
	}
	return t.TaskActionID
}

func (t *TaskActionsServiceCloseResponse) GetTaskView() *TaskView {
	if t == nil {
		return nil
	}
	return t.TaskView
}
