// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RequestData struct {
}

// TaskServiceCreateGrantRequest - Create a grant task.
type TaskServiceCreateGrantRequest struct {
	// The ID of the app entitlement to grant access to.
	AppEntitlementID string `json:"appEntitlementId"`
	// The ID of the app that is associated with the entitlement.
	AppID string `json:"appId"`
	// The ID of the app user to grant access for. This field and identityUserId cannot both be set for a given request.
	AppUserID *string `json:"appUserId,omitempty"`
	// The description of the request.
	Description *string `json:"description,omitempty"`
	// Boolean stating whether or not the task is marked as emergency access.
	EmergencyAccess *bool   `json:"emergencyAccess,omitempty"`
	GrantDuration   *string `json:"grantDuration,omitempty"`
	// The ID of the user associated with the app user we are granting access for. This field cannot be set if appUserID is also set.
	IdentityUserID *string      `json:"identityUserId,omitempty"`
	RequestData    *RequestData `json:"requestData,omitempty"`
	// The TaskGrantSource message tracks which external URL was the source of the specificed grant ticket.
	TaskGrantSource *TaskGrantSource `json:"source,omitempty"`
}

func (t *TaskServiceCreateGrantRequest) GetAppEntitlementID() string {
	if t == nil {
		return ""
	}
	return t.AppEntitlementID
}

func (t *TaskServiceCreateGrantRequest) GetAppID() string {
	if t == nil {
		return ""
	}
	return t.AppID
}

func (t *TaskServiceCreateGrantRequest) GetAppUserID() *string {
	if t == nil {
		return nil
	}
	return t.AppUserID
}

func (t *TaskServiceCreateGrantRequest) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TaskServiceCreateGrantRequest) GetEmergencyAccess() *bool {
	if t == nil {
		return nil
	}
	return t.EmergencyAccess
}

func (t *TaskServiceCreateGrantRequest) GetGrantDuration() *string {
	if t == nil {
		return nil
	}
	return t.GrantDuration
}

func (t *TaskServiceCreateGrantRequest) GetIdentityUserID() *string {
	if t == nil {
		return nil
	}
	return t.IdentityUserID
}

func (t *TaskServiceCreateGrantRequest) GetRequestData() *RequestData {
	if t == nil {
		return nil
	}
	return t.RequestData
}

func (t *TaskServiceCreateGrantRequest) GetTaskGrantSource() *TaskGrantSource {
	if t == nil {
		return nil
	}
	return t.TaskGrantSource
}
