// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The TaskActionsServiceDenyRequest object lets you deny a task.
type TaskActionsServiceDenyRequest struct {
	// The comment attached to the request.
	Comment *string `json:"comment,omitempty"`
	// The ID of the currently policy step. This is the step you want to deny.
	PolicyStepID *string `json:"policyStepId,omitempty"`
}

func (o *TaskActionsServiceDenyRequest) GetComment() *string {
	if o == nil {
		return nil
	}
	return o.Comment
}

func (o *TaskActionsServiceDenyRequest) GetPolicyStepID() *string {
	if o == nil {
		return nil
	}
	return o.PolicyStepID
}
