// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/internal/utils"
	"time"
)

// TBEgressPolicyDefaultOutcome - The defaultOutcome field.
type TBEgressPolicyDefaultOutcome string

const (
	TBEgressPolicyDefaultOutcomeTbEgressOutcomeUnspecified TBEgressPolicyDefaultOutcome = "TB_EGRESS_OUTCOME_UNSPECIFIED"
	TBEgressPolicyDefaultOutcomeTbEgressOutcomeAllowed     TBEgressPolicyDefaultOutcome = "TB_EGRESS_OUTCOME_ALLOWED"
	TBEgressPolicyDefaultOutcomeTbEgressOutcomeDenied      TBEgressPolicyDefaultOutcome = "TB_EGRESS_OUTCOME_DENIED"
)

func (e TBEgressPolicyDefaultOutcome) ToPointer() *TBEgressPolicyDefaultOutcome {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TBEgressPolicyDefaultOutcome) IsExact() bool {
	if e != nil {
		switch *e {
		case "TB_EGRESS_OUTCOME_UNSPECIFIED", "TB_EGRESS_OUTCOME_ALLOWED", "TB_EGRESS_OUTCOME_DENIED":
			return true
		}
	}
	return false
}

// TBEgressPolicy is the typed policy document for one TB instance. Binds
//
//	per-instance, not per-tenant-across-instances, keyed by tb_instance_id
//	exactly as discovery reports it.
type TBEgressPolicy struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// The defaultDenyReason field.
	DefaultDenyReason *string `json:"defaultDenyReason,omitempty"`
	// The defaultOutcome field.
	DefaultOutcome *TBEgressPolicyDefaultOutcome `json:"defaultOutcome,omitempty"`
	// Opaque, bumped on every successful save -- TB's change detector.
	//  Stamped as "c1-gen-<N>".
	Generation *string `json:"generation,omitempty"`
	// The rules field.
	Rules []TBEgressRule `json:"rules,omitempty"`
	// The tbInstanceId field.
	TbInstanceID *string `json:"tbInstanceId,omitempty"`
	// The tenantId field.
	TenantID  *string    `json:"tenantId,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

func (t TBEgressPolicy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TBEgressPolicy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TBEgressPolicy) GetCreatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.CreatedAt
}

func (t *TBEgressPolicy) GetDefaultDenyReason() *string {
	if t == nil {
		return nil
	}
	return t.DefaultDenyReason
}

func (t *TBEgressPolicy) GetDefaultOutcome() *TBEgressPolicyDefaultOutcome {
	if t == nil {
		return nil
	}
	return t.DefaultOutcome
}

func (t *TBEgressPolicy) GetGeneration() *string {
	if t == nil {
		return nil
	}
	return t.Generation
}

func (t *TBEgressPolicy) GetRules() []TBEgressRule {
	if t == nil {
		return nil
	}
	return t.Rules
}

func (t *TBEgressPolicy) GetTbInstanceID() *string {
	if t == nil {
		return nil
	}
	return t.TbInstanceID
}

func (t *TBEgressPolicy) GetTenantID() *string {
	if t == nil {
		return nil
	}
	return t.TenantID
}

func (t *TBEgressPolicy) GetUpdatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.UpdatedAt
}
