// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// TraceAllocationPeriod - The period field.
type TraceAllocationPeriod string

const (
	TraceAllocationPeriodPeriodKindUnspecified TraceAllocationPeriod = "PERIOD_KIND_UNSPECIFIED"
	TraceAllocationPeriodPeriodKindDaily       TraceAllocationPeriod = "PERIOD_KIND_DAILY"
	TraceAllocationPeriodPeriodKindWeekly      TraceAllocationPeriod = "PERIOD_KIND_WEEKLY"
	TraceAllocationPeriodPeriodKindMonthly     TraceAllocationPeriod = "PERIOD_KIND_MONTHLY"
	TraceAllocationPeriodPeriodKindQuarterly   TraceAllocationPeriod = "PERIOD_KIND_QUARTERLY"
	TraceAllocationPeriodPeriodKindYearly      TraceAllocationPeriod = "PERIOD_KIND_YEARLY"
)

func (e TraceAllocationPeriod) ToPointer() *TraceAllocationPeriod {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TraceAllocationPeriod) IsExact() bool {
	if e != nil {
		switch *e {
		case "PERIOD_KIND_UNSPECIFIED", "PERIOD_KIND_DAILY", "PERIOD_KIND_WEEKLY", "PERIOD_KIND_MONTHLY", "PERIOD_KIND_QUARTERLY", "PERIOD_KIND_YEARLY":
			return true
		}
	}
	return false
}

// TraceAllocation records one admitted scope, the row that supplied its
//
//	resolved limit, and the historical limit and period.
type TraceAllocation struct {
	// The budgetKey field.
	BudgetKey *string        `json:"budgetKey,omitempty"`
	Limit     *ResolvedLimit `json:"limit,omitempty"`
	// The period field.
	Period *TraceAllocationPeriod `json:"period,omitempty"`
	Source *AuthorityRef          `json:"source,omitempty"`
}

func (t *TraceAllocation) GetBudgetKey() *string {
	if t == nil {
		return nil
	}
	return t.BudgetKey
}

func (t *TraceAllocation) GetLimit() *ResolvedLimit {
	if t == nil {
		return nil
	}
	return t.Limit
}

func (t *TraceAllocation) GetPeriod() *TraceAllocationPeriod {
	if t == nil {
		return nil
	}
	return t.Period
}

func (t *TraceAllocation) GetSource() *AuthorityRef {
	if t == nil {
		return nil
	}
	return t.Source
}
