// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The UpdateAppUsageControlsRequest message contains the AppUsageControls object to update and the update mask.
type UpdateAppUsageControlsRequest struct {
	// The AppUsageControls object describes some peripheral configuration for an app.
	AppUsageControls *AppUsageControls `json:"appUsageControls,omitempty"`
	UpdateMask       *string           `json:"updateMask,omitempty"`
}

func (u *UpdateAppUsageControlsRequest) GetAppUsageControls() *AppUsageControls {
	if u == nil {
		return nil
	}
	return u.AppUsageControls
}

func (u *UpdateAppUsageControlsRequest) GetUpdateMask() *string {
	if u == nil {
		return nil
	}
	return u.UpdateMask
}
