// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The UpdateUserNotificationSettingsRequest message.
type UpdateUserNotificationSettingsRequest struct {
	// ChannelSettings groups notification preferences for all supported channels.
	ChannelSettings *ChannelSettings `json:"channelSettings,omitempty"`
}

func (u *UpdateUserNotificationSettingsRequest) GetChannelSettings() *ChannelSettings {
	if u == nil {
		return nil
	}
	return u.ChannelSettings
}
