// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The UserProperties message.
type UserProperties struct {
	// The displayNameCel field.
	DisplayNameCel *string `json:"displayNameCel,omitempty"`
	// The emailCel field.
	EmailCel *string `json:"emailCel,omitempty"`
	// The profileAttributeCel field.
	ProfileAttributeCel *string `json:"profileAttributeCel,omitempty"`
	// The usernameCel field.
	UsernameCel *string `json:"usernameCel,omitempty"`
}

func (o *UserProperties) GetDisplayNameCel() *string {
	if o == nil {
		return nil
	}
	return o.DisplayNameCel
}

func (o *UserProperties) GetEmailCel() *string {
	if o == nil {
		return nil
	}
	return o.EmailCel
}

func (o *UserProperties) GetProfileAttributeCel() *string {
	if o == nil {
		return nil
	}
	return o.ProfileAttributeCel
}

func (o *UserProperties) GetUsernameCel() *string {
	if o == nil {
		return nil
	}
	return o.UsernameCel
}
