// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 151c40865469

package shared

// VaultServiceDeleteResponse - Empty response body. Status code indicates success.
type VaultServiceDeleteResponse struct {
}
