// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// VirtualMCPServerServiceUpdateRequest updates mutable Virtual MCP Server fields.
type VirtualMCPServerServiceUpdateRequest struct {
	UpdateMask       *string           `json:"updateMask,omitempty"`
	VirtualMcpServer *VirtualMCPServer `json:"virtualMcpServer,omitempty"`
}

func (v *VirtualMCPServerServiceUpdateRequest) GetUpdateMask() *string {
	if v == nil {
		return nil
	}
	return v.UpdateMask
}

func (v *VirtualMCPServerServiceUpdateRequest) GetVirtualMcpServer() *VirtualMCPServer {
	if v == nil {
		return nil
	}
	return v.VirtualMcpServer
}
