// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/internal/utils"
	"time"
)

// VirtualMCPServerState - Current lifecycle state.
type VirtualMCPServerState string

const (
	VirtualMCPServerStateVirtualMcpServerStateUnspecified VirtualMCPServerState = "VIRTUAL_MCP_SERVER_STATE_UNSPECIFIED"
	VirtualMCPServerStateVirtualMcpServerStateActive      VirtualMCPServerState = "VIRTUAL_MCP_SERVER_STATE_ACTIVE"
	VirtualMCPServerStateVirtualMcpServerStateDisabled    VirtualMCPServerState = "VIRTUAL_MCP_SERVER_STATE_DISABLED"
)

func (e VirtualMCPServerState) ToPointer() *VirtualMCPServerState {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *VirtualMCPServerState) IsExact() bool {
	if e != nil {
		switch *e {
		case "VIRTUAL_MCP_SERVER_STATE_UNSPECIFIED", "VIRTUAL_MCP_SERVER_STATE_ACTIVE", "VIRTUAL_MCP_SERVER_STATE_DISABLED":
			return true
		}
	}
	return false
}

// VirtualMCPServer is a tenant-managed MCP endpoint backed by one composition.
//
// This message contains a oneof named composition. Only a single field of the following list may be set at a time:
//   - mappedSource
//   - assignedTools
type VirtualMCPServer struct {
	// Permit owner-scoped personal MCP sources on supported compositions.
	AllowPersonalSources *bool                    `json:"allowPersonalSources,omitempty"`
	AssignedTools        *VirtualMCPAssignedTools `json:"assignedTools,omitempty"`
	CreatedAt            *time.Time               `json:"createdAt,omitempty"`
	// Human-readable name shown to administrators and users.
	DisplayName *string `json:"displayName,omitempty"`
	// Immutable unique identifier for this Virtual MCP Server.
	ID           *string                 `json:"id,omitempty"`
	MappedSource *VirtualMCPMappedSource `json:"mappedSource,omitempty"`
	Presentation *VirtualMCPPresentation `json:"presentation,omitempty"`
	// When true, require an active ConductorOne-managed device in addition to
	//  DPoP. require_device_trust=true requires require_dpop=true.
	RequireDeviceTrust *bool `json:"requireDeviceTrust,omitempty"`
	// When true, require DPoP proof-of-possession for OAuth access tokens.
	RequireDpop *bool `json:"requireDpop,omitempty"`
	// Current canonical lowercase route segment, unique for the tenant. Renaming
	//  preserves the previous slug as a deprecated alias until it is reused.
	Slug *string `json:"slug,omitempty"`
	// Current lifecycle state.
	State     *VirtualMCPServerState `json:"state,omitempty"`
	UpdatedAt *time.Time             `json:"updatedAt,omitempty"`
	// Identifier of the governed `use` entitlement for this server. This is the
	//  same immutable identifier as id and is returned for access-profile setup.
	UseEntitlementID *string `json:"useEntitlementId,omitempty"`
}

func (v VirtualMCPServer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VirtualMCPServer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VirtualMCPServer) GetAllowPersonalSources() *bool {
	if v == nil {
		return nil
	}
	return v.AllowPersonalSources
}

func (v *VirtualMCPServer) GetAssignedTools() *VirtualMCPAssignedTools {
	if v == nil {
		return nil
	}
	return v.AssignedTools
}

func (v *VirtualMCPServer) GetCreatedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.CreatedAt
}

func (v *VirtualMCPServer) GetDisplayName() *string {
	if v == nil {
		return nil
	}
	return v.DisplayName
}

func (v *VirtualMCPServer) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *VirtualMCPServer) GetMappedSource() *VirtualMCPMappedSource {
	if v == nil {
		return nil
	}
	return v.MappedSource
}

func (v *VirtualMCPServer) GetPresentation() *VirtualMCPPresentation {
	if v == nil {
		return nil
	}
	return v.Presentation
}

func (v *VirtualMCPServer) GetRequireDeviceTrust() *bool {
	if v == nil {
		return nil
	}
	return v.RequireDeviceTrust
}

func (v *VirtualMCPServer) GetRequireDpop() *bool {
	if v == nil {
		return nil
	}
	return v.RequireDpop
}

func (v *VirtualMCPServer) GetSlug() *string {
	if v == nil {
		return nil
	}
	return v.Slug
}

func (v *VirtualMCPServer) GetState() *VirtualMCPServerState {
	if v == nil {
		return nil
	}
	return v.State
}

func (v *VirtualMCPServer) GetUpdatedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.UpdatedAt
}

func (v *VirtualMCPServer) GetUseEntitlementID() *string {
	if v == nil {
		return nil
	}
	return v.UseEntitlementID
}
