// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 385a64afab33

package shared

// The WorkloadFederationServiceDeleteTrustRequest message.
type WorkloadFederationServiceDeleteTrustRequest struct {
}
