// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// The WorkloadFederationServiceGetProviderResponse message.
type WorkloadFederationServiceGetProviderResponse struct {
	// WorkloadFederationProvider represents a tenant-level OIDC issuer registration.
	WorkloadFederationProvider *WorkloadFederationProvider `json:"provider,omitempty"`
}

func (w *WorkloadFederationServiceGetProviderResponse) GetWorkloadFederationProvider() *WorkloadFederationProvider {
	if w == nil {
		return nil
	}
	return w.WorkloadFederationProvider
}
