// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// XAAAccessProfileServiceGetByAppEntitlementIDResponse - XAAAccessProfileServiceGetByAppEntitlementIdResponse returns the matched
//
//	profile.
type XAAAccessProfileServiceGetByAppEntitlementIDResponse struct {
	// XAAAccessProfile is a requestable bundle of scopes for one resource server.
	XAAAccessProfile *XAAAccessProfile `json:"accessProfile,omitempty"`
}

func (x *XAAAccessProfileServiceGetByAppEntitlementIDResponse) GetXAAAccessProfile() *XAAAccessProfile {
	if x == nil {
		return nil
	}
	return x.XAAAccessProfile
}
