// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// XAAScopeServiceListHistoryResponse returns scope history entries.
type XAAScopeServiceListHistoryResponse struct {
	// The page of history entries, newest first.
	List []XAAScopeHistoryEntry `json:"list,omitempty"`
	// Pagination token for the next page, or empty if there are no more results.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

func (x *XAAScopeServiceListHistoryResponse) GetList() []XAAScopeHistoryEntry {
	if x == nil {
		return nil
	}
	return x.List
}

func (x *XAAScopeServiceListHistoryResponse) GetNextPageToken() *string {
	if x == nil {
		return nil
	}
	return x.NextPageToken
}
