// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/conductorone/terraform-provider-conductorone/internal/provider/typeconvert"
	tfTypes "github.com/conductorone/terraform-provider-conductorone/internal/provider/types"
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/operations"
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *AppResourceDataSourceModel) RefreshFromSharedAppResource(ctx context.Context, resp *shared.AppResource) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AppID = types.StringPointerValue(resp.AppID)
		r.AppResourceTypeID = types.StringPointerValue(resp.AppResourceTypeID)
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.DeletedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.DeletedAt))
		r.Description = types.StringPointerValue(resp.Description)
		r.DisplayName = types.StringPointerValue(resp.DisplayName)
		r.GrantCount = types.StringPointerValue(resp.GrantCount)
		r.ID = types.StringPointerValue(resp.ID)
		r.MatchBatonID = types.StringPointerValue(resp.MatchBatonID)
		r.ParentAppResourceID = types.StringPointerValue(resp.ParentAppResourceID)
		r.ParentAppResourceTypeID = types.StringPointerValue(resp.ParentAppResourceTypeID)
		if resp.SecretTrait == nil {
			r.SecretTrait = nil
		} else {
			r.SecretTrait = &tfTypes.SecretTrait{}
			r.SecretTrait.IdentityAppUserID = types.StringPointerValue(resp.SecretTrait.IdentityAppUserID)
			r.SecretTrait.LastUsedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.SecretTrait.LastUsedAt))
			r.SecretTrait.SecretCreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.SecretTrait.SecretCreatedAt))
			r.SecretTrait.SecretExpiresAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.SecretTrait.SecretExpiresAt))
		}
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
	}

	return diags
}

func (r *AppResourceDataSourceModel) RefreshFromSharedAppResourceServiceGetResponse(ctx context.Context, resp *shared.AppResourceServiceGetResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedAppResourceView(ctx, resp.AppResourceView)...)

		if diags.HasError() {
			return diags
		}

		if resp.Expanded != nil {
		}
	}

	return diags
}

func (r *AppResourceDataSourceModel) RefreshFromSharedAppResourceView(ctx context.Context, resp *shared.AppResourceView) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedAppResource(ctx, resp.AppResource)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *AppResourceDataSourceModel) ToOperationsC1APIAppV1AppResourceServiceGetRequest(ctx context.Context) (*operations.C1APIAppV1AppResourceServiceGetRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var appID string
	appID = r.AppID.ValueString()

	var appResourceTypeID string
	appResourceTypeID = r.AppResourceTypeID.ValueString()

	var id string
	id = r.ID.ValueString()

	out := operations.C1APIAppV1AppResourceServiceGetRequest{
		AppID:             appID,
		AppResourceTypeID: appResourceTypeID,
		ID:                id,
	}

	return &out, diags
}
