// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	speakeasy_stringplanmodifier "github.com/conductorone/terraform-provider-conductorone/internal/planmodifiers/stringplanmodifier"
	tfTypes "github.com/conductorone/terraform-provider-conductorone/internal/provider/types"
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ConnectorOwnerUserResource{}
var _ resource.ResourceWithImportState = &ConnectorOwnerUserResource{}

func NewConnectorOwnerUserResource() resource.Resource {
	return &ConnectorOwnerUserResource{}
}

// ConnectorOwnerUserResource defines the resource implementation.
type ConnectorOwnerUserResource struct {
	// Provider configured SDK client.
	client *sdk.ConductoroneAPI
}

// ConnectorOwnerUserResourceModel describes the resource data model.
type ConnectorOwnerUserResourceModel struct {
	AppID       types.String     `tfsdk:"app_id"`
	ConnectorID types.String     `tfsdk:"connector_id"`
	CreatedAt   types.String     `tfsdk:"created_at"`
	RoleSlug    types.String     `tfsdk:"role_slug"`
	User        *tfTypes.User    `tfsdk:"user"`
	UserRef     *tfTypes.UserRef `tfsdk:"user_ref"`
	UserRefID   types.String     `tfsdk:"user_ref_id"`
}

func (r *ConnectorOwnerUserResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_connector_owner_user"
}

func (r *ConnectorOwnerUserResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "ConnectorOwnerUser Resource",
		Attributes: map[string]schema.Attribute{
			"app_id": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Description: `The appId field. Requires replacement if changed.`,
			},
			"connector_id": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Description: `The connectorId field. Requires replacement if changed.`,
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"role_slug": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Description: `The roleSlug field. Requires replacement if changed.`,
			},
			"user": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Computed: true,
					},
					"delegated_user_id": schema.StringAttribute{
						Computed:    true,
						Description: `The id of the user to whom tasks will be automatically reassigned to.`,
					},
					"deleted_at": schema.StringAttribute{
						Computed: true,
					},
					"department": schema.StringAttribute{
						Computed:    true,
						Description: `The department which the user belongs to in the organization.`,
					},
					"department_sources": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"app_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appId field.`,
								},
								"app_user_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserId field.`,
								},
								"app_user_profile_attribute_key": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserProfileAttributeKey field.`,
								},
								"user_attribute_mapping_id": schema.StringAttribute{
									Computed:    true,
									Description: `The userAttributeMappingId field.`,
								},
								"value": schema.StringAttribute{
									Computed:    true,
									Description: `The value field.`,
								},
							},
						},
						Description: `A list of objects mapped based on department attribute mappings configured in the system.`,
					},
					"directory_ids": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
						Description: `A list of unique ids that represent different directories.`,
					},
					"directory_status": schema.StringAttribute{
						Computed:    true,
						Description: `The status of the user in the directory.`,
					},
					"directory_status_sources": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"app_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appId field.`,
								},
								"app_user_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserId field.`,
								},
								"app_user_profile_attribute_key": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserProfileAttributeKey field.`,
								},
								"user_attribute_mapping_id": schema.StringAttribute{
									Computed:    true,
									Description: `The userAttributeMappingId field.`,
								},
								"value": schema.StringAttribute{
									Computed:    true,
									Description: `The value field.`,
								},
							},
						},
						Description: `A list of objects mapped based on directoryStatus attribute mappings configured in the system.`,
					},
					"display_name": schema.StringAttribute{
						Computed:    true,
						Description: `The display name of the user.`,
					},
					"email": schema.StringAttribute{
						Computed:    true,
						Description: `This is the user's email.`,
					},
					"email_sources": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"app_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appId field.`,
								},
								"app_user_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserId field.`,
								},
								"app_user_profile_attribute_key": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserProfileAttributeKey field.`,
								},
								"user_attribute_mapping_id": schema.StringAttribute{
									Computed:    true,
									Description: `The userAttributeMappingId field.`,
								},
								"value": schema.StringAttribute{
									Computed:    true,
									Description: `The value field.`,
								},
							},
						},
						Description: `A list of source data for the email attribute.`,
					},
					"emails": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
						Description: `This is a list of all of the user's emails from app users.`,
					},
					"employee_id_sources": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"app_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appId field.`,
								},
								"app_user_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserId field.`,
								},
								"app_user_profile_attribute_key": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserProfileAttributeKey field.`,
								},
								"user_attribute_mapping_id": schema.StringAttribute{
									Computed:    true,
									Description: `The userAttributeMappingId field.`,
								},
								"value": schema.StringAttribute{
									Computed:    true,
									Description: `The value field.`,
								},
							},
						},
						Description: `A list of source data for the employee IDs attribute.`,
					},
					"employee_ids": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
						Description: `This is a list of all of the user's employee IDs from app users.`,
					},
					"employment_status": schema.StringAttribute{
						Computed:    true,
						Description: `The users employment status.`,
					},
					"employment_status_sources": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"app_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appId field.`,
								},
								"app_user_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserId field.`,
								},
								"app_user_profile_attribute_key": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserProfileAttributeKey field.`,
								},
								"user_attribute_mapping_id": schema.StringAttribute{
									Computed:    true,
									Description: `The userAttributeMappingId field.`,
								},
								"value": schema.StringAttribute{
									Computed:    true,
									Description: `The value field.`,
								},
							},
						},
						Description: `A list of objects mapped based on employmentStatus attribute mappings configured in the system.`,
					},
					"employment_type": schema.StringAttribute{
						Computed:    true,
						Description: `The employment type of the user.`,
					},
					"employment_type_sources": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"app_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appId field.`,
								},
								"app_user_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserId field.`,
								},
								"app_user_profile_attribute_key": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserProfileAttributeKey field.`,
								},
								"user_attribute_mapping_id": schema.StringAttribute{
									Computed:    true,
									Description: `The userAttributeMappingId field.`,
								},
								"value": schema.StringAttribute{
									Computed:    true,
									Description: `The value field.`,
								},
							},
						},
						Description: `A list of objects mapped based on employmentType attribute mappings configured in the system.`,
					},
					"id": schema.StringAttribute{
						Computed:    true,
						Description: `A unique identifier of the user.`,
					},
					"job_title": schema.StringAttribute{
						Computed:    true,
						Description: `The job title of the user.`,
					},
					"job_title_sources": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"app_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appId field.`,
								},
								"app_user_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserId field.`,
								},
								"app_user_profile_attribute_key": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserProfileAttributeKey field.`,
								},
								"user_attribute_mapping_id": schema.StringAttribute{
									Computed:    true,
									Description: `The userAttributeMappingId field.`,
								},
								"value": schema.StringAttribute{
									Computed:    true,
									Description: `The value field.`,
								},
							},
						},
						Description: `A list of objects mapped based on jobTitle attribute mappings configured in the system.`,
					},
					"manager_ids": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
						Description: `A list of ids of the user's managers.`,
					},
					"manager_sources": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"app_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appId field.`,
								},
								"app_user_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserId field.`,
								},
								"app_user_profile_attribute_key": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserProfileAttributeKey field.`,
								},
								"user_attribute_mapping_id": schema.StringAttribute{
									Computed:    true,
									Description: `The userAttributeMappingId field.`,
								},
								"value": schema.StringAttribute{
									Computed:    true,
									Description: `The value field.`,
								},
							},
						},
						Description: `A list of objects mapped based on managerId attribute mappings configured in the system.`,
					},
					"origin": schema.StringAttribute{
						Computed:    true,
						Description: `The origin of the user, describing who owns the user's lifecycle.`,
					},
					"profile": schema.SingleNestedAttribute{
						Computed: true,
					},
					"role_ids": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
						Description: `A list of unique identifiers that maps to ConductorOne's user roles let you assign users permissions tailored to the work they do in the software.`,
					},
					"status": schema.StringAttribute{
						Computed:    true,
						Description: `The status of the user in the system.`,
					},
					"type": schema.StringAttribute{
						Computed:    true,
						Description: `The type of the user.`,
					},
					"updated_at": schema.StringAttribute{
						Computed: true,
					},
					"username": schema.StringAttribute{
						Computed:    true,
						Description: `This is the user's primary username. Typically sourced from the primary directory.`,
					},
					"username_sources": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"app_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appId field.`,
								},
								"app_user_id": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserId field.`,
								},
								"app_user_profile_attribute_key": schema.StringAttribute{
									Computed:    true,
									Description: `The appUserProfileAttributeKey field.`,
								},
								"user_attribute_mapping_id": schema.StringAttribute{
									Computed:    true,
									Description: `The userAttributeMappingId field.`,
								},
								"value": schema.StringAttribute{
									Computed:    true,
									Description: `The value field.`,
								},
							},
						},
						Description: `A list of source data for the usernames attribute.`,
					},
					"usernames": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
						Description: `This is a list of all of the user's usernames from app users.`,
					},
				},
				Description: `The User object provides all of the details for an user, as well as some configuration.`,
			},
			"user_ref": schema.SingleNestedAttribute{
				Optional: true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplaceIfConfigured(),
				},
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
						},
						Description: `The id of the user. Requires replacement if changed.`,
					},
				},
				Description: `A reference to a user. Requires replacement if changed.`,
			},
			"user_ref_id": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
				Description: `Requires replacement if changed.`,
			},
		},
	}
}

func (r *ConnectorOwnerUserResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.ConductoroneAPI)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.ConductoroneAPI, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *ConnectorOwnerUserResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *ConnectorOwnerUserResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsC1APIAppV2ConnectorOwnersCreateUserOwnerRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.ConnectorOwnersV2.CreateUserOwner(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.CreateConnectorUserOwnerResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedCreateConnectorUserOwnerResponse(ctx, res.CreateConnectorUserOwnerResponse)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ConnectorOwnerUserResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *ConnectorOwnerUserResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsC1APIAppV2ConnectorOwnersGetUserOwnerRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.ConnectorOwnersV2.GetUserOwner(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.GetConnectorUserOwnerResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedGetConnectorUserOwnerResponse(ctx, res.GetConnectorUserOwnerResponse)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ConnectorOwnerUserResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *ConnectorOwnerUserResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	// Not Implemented; all attributes marked as RequiresReplace

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ConnectorOwnerUserResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *ConnectorOwnerUserResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsC1APIAppV2ConnectorOwnersDeleteUserOwnerRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.ConnectorOwnersV2.DeleteUserOwner(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	switch res.StatusCode {
	case 200, 404:
		break
	default:
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}

}

func (r *ConnectorOwnerUserResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	dec := json.NewDecoder(bytes.NewReader([]byte(req.ID)))
	dec.DisallowUnknownFields()
	var data struct {
		AppID       string `json:"app_id"`
		ConnectorID string `json:"connector_id"`
		RoleSlug    string `json:"role_slug"`
		UserRefID   string `json:"user_ref_id"`
	}

	if err := dec.Decode(&data); err != nil {
		resp.Diagnostics.AddError("Invalid ID", `The import ID is not valid. It is expected to be a JSON object string with the format: '{"app_id": "...", "connector_id": "...", "role_slug": "...", "user_ref_id": "..."}': `+err.Error())
		return
	}

	if len(data.AppID) == 0 {
		resp.Diagnostics.AddError("Missing required field", `The field app_id is required but was not found in the json encoded ID.`)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("app_id"), data.AppID)...)
	if len(data.ConnectorID) == 0 {
		resp.Diagnostics.AddError("Missing required field", `The field connector_id is required but was not found in the json encoded ID.`)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("connector_id"), data.ConnectorID)...)
	if len(data.RoleSlug) == 0 {
		resp.Diagnostics.AddError("Missing required field", `The field role_slug is required but was not found in the json encoded ID.`)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("role_slug"), data.RoleSlug)...)
	if len(data.UserRefID) == 0 {
		resp.Diagnostics.AddError("Missing required field", `The field user_ref_id is required but was not found in the json encoded ID.`)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("user_ref_id"), data.UserRefID)...)
}
