// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/conductorone/terraform-provider-conductorone/internal/provider/types"
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &GoLinkDataSource{}
var _ datasource.DataSourceWithConfigure = &GoLinkDataSource{}

func NewGoLinkDataSource() datasource.DataSource {
	return &GoLinkDataSource{}
}

// GoLinkDataSource is the data source implementation.
type GoLinkDataSource struct {
	// Provider configured SDK client.
	client *sdk.ConductoroneAPI
}

// GoLinkDataSourceModel describes the data model.
type GoLinkDataSourceModel struct {
	CreatedAt      types.String                `tfsdk:"created_at"`
	CurrentVersion types.Int32                 `tfsdk:"current_version"`
	Delete         types.Bool                  `tfsdk:"delete"`
	DeletedAt      types.String                `tfsdk:"deleted_at"`
	Description    types.String                `tfsdk:"description"`
	DisplayName    types.String                `tfsdk:"display_name"`
	Edit           types.Bool                  `tfsdk:"edit"`
	Extra          map[string]types.Bool       `tfsdk:"extra"`
	ID             types.String                `tfsdk:"id"`
	NextPageToken  types.String                `tfsdk:"next_page_token"`
	PageSize       types.Int32                 `queryParam:"style=form,explode=true,name=page_size" tfsdk:"page_size"`
	PageToken      types.String                `queryParam:"style=form,explode=true,name=page_token" tfsdk:"page_token"`
	Prerequisite   *tfTypes.GoLinkPrerequisite `tfsdk:"prerequisite"`
	Read           types.Bool                  `tfsdk:"read"`
	Routes         []tfTypes.GoLinkRouteConfig `tfsdk:"routes"`
	Status         types.String                `tfsdk:"status"`
	Target         *tfTypes.GoLinkTarget       `tfsdk:"target"`
	UpdatedAt      types.String                `tfsdk:"updated_at"`
}

// Metadata returns the data source type name.
func (r *GoLinkDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_go_link"
}

// Schema defines the schema for the data source.
func (r *GoLinkDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "GoLink DataSource",

		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"current_version": schema.Int32Attribute{
				Computed:    true,
				Description: `The currentVersion field.`,
			},
			"delete": schema.BoolAttribute{
				Computed:    true,
				Description: `The delete field.`,
			},
			"deleted_at": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: `The description field.`,
			},
			"display_name": schema.StringAttribute{
				Computed:    true,
				Description: `The displayName field.`,
			},
			"edit": schema.BoolAttribute{
				Computed:    true,
				Description: `The edit field.`,
			},
			"extra": schema.MapAttribute{
				Computed:    true,
				ElementType: types.BoolType,
				Description: `The extra field.`,
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: `The id field.`,
			},
			"next_page_token": schema.StringAttribute{
				Computed:    true,
				Description: `The nextPageToken field.`,
			},
			"page_size": schema.Int32Attribute{
				Optional: true,
			},
			"page_token": schema.StringAttribute{
				Optional: true,
			},
			"prerequisite": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"app_entitlement_id": schema.StringAttribute{
						Computed:    true,
						Description: `The appEntitlementId field.`,
					},
					"app_id": schema.StringAttribute{
						Computed:    true,
						Description: `The appId field.`,
					},
				},
				Description: `The GoLinkPrerequisite message.`,
			},
			"read": schema.BoolAttribute{
				Computed:    true,
				Description: `The read field.`,
			},
			"routes": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"is_canonical": schema.BoolAttribute{
							Computed:    true,
							Description: `The isCanonical field.`,
						},
						"route_template": schema.StringAttribute{
							Computed: true,
							MarkdownDescription: `The route template with optional named parameters.` + "\n" +
								` Exact routes: "jira", "jira/create"` + "\n" +
								` Glob routes: "jira/{ticket_id}", "aws/{path}"`,
						},
					},
				},
				Description: `The routes field.`,
			},
			"status": schema.StringAttribute{
				Computed:    true,
				Description: `The status field.`,
			},
			"target": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"action": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"action_id": schema.StringAttribute{
								Computed:    true,
								Description: `The actionId field.`,
							},
						},
						Description: `The GoLinkActionTarget message.`,
					},
					"chooser": schema.StringAttribute{
						CustomType:  jsontypes.NormalizedType{},
						Computed:    true,
						Description: `Parsed as JSON.`,
					},
					"redirect": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"url_template": schema.StringAttribute{
								Computed: true,
								MarkdownDescription: `URL template with named placeholders matching route parameters.` + "\n" +
									` e.g., "https://jira.internal/browse/{ticket_id}"`,
							},
						},
						Description: `The GoLinkRedirectTarget message.`,
					},
				},
				MarkdownDescription: `The GoLinkTarget message.` + "\n" +
					`` + "\n" +
					`This message contains a oneof named target. Only a single field of the following list may be set at a time:` + "\n" +
					`  - redirect` + "\n" +
					`  - action` + "\n" +
					`  - chooser`,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (r *GoLinkDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.ConductoroneAPI)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.ConductoroneAPI, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *GoLinkDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *GoLinkDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsC1APIGolinkV1GoLinkServiceListRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.GoLink.List(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.GoLinkServiceListResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedGoLinkServiceListResponse(ctx, res.GoLinkServiceListResponse)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
