// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ApprovalInput struct {
	AllowReassignment         types.Bool                     `tfsdk:"allow_reassignment"`
	AppGroupApproval          *AppGroupApprovalInput         `tfsdk:"app_group_approval"`
	AppOwnerApproval          *AppOwnerApprovalInput         `tfsdk:"app_owner_approval"`
	Assigned                  types.Bool                     `tfsdk:"assigned"`
	EntitlementOwnerApproval  *EntitlementOwnerApprovalInput `tfsdk:"entitlement_owner_approval"`
	ExpressionApproval        *ExpressionApprovalInput       `tfsdk:"expression_approval"`
	ManagerApproval           *ManagerApprovalInput          `tfsdk:"manager_approval"`
	RequireApprovalReason     types.Bool                     `tfsdk:"require_approval_reason"`
	RequireReassignmentReason types.Bool                     `tfsdk:"require_reassignment_reason"`
	SelfApproval              *SelfApprovalInput             `tfsdk:"self_approval"`
	UserApproval              *UserApprovalInput             `tfsdk:"user_approval"`
}
