// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Rule struct {
	Condition types.String `tfsdk:"condition"`
	PolicyKey types.String `tfsdk:"policy_key"`
}
