// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AccessReviewInclusionScope struct {
	AppUserStatuses            []types.String                         `tfsdk:"app_user_statuses"`
	AppUserTypes               []types.String                         `tfsdk:"app_user_types"`
	ManagerIds                 []types.String                         `tfsdk:"manager_ids"`
	MultiUserProfileAttributes map[string]IncludedUserAttributeValues `tfsdk:"multi_user_profile_attributes"`
	NoAccountOwners            types.Bool                             `tfsdk:"no_account_owners"`
	UserIds                    []types.String                         `tfsdk:"user_ids"`
	UserStatuses               []types.String                         `tfsdk:"user_statuses"`
}
