// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 94e577b4031d

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CampaignInsights struct {
	Markdown types.String `tfsdk:"markdown"`
}
