// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 77f032dae211

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Directory struct {
	DirectoryAccountFilterAll *DirectoryAccountFilterAll `tfsdk:"directory_account_filter_all"`
	DirectoryAccountFilterCel *DirectoryAccountFilterCel `tfsdk:"directory_account_filter_cel"`
	DirectoryMergeConfig      *DirectoryMergeConfig      `tfsdk:"directory_merge_config"`
	AppID                     types.String               `tfsdk:"app_id"`
	CreatedAt                 types.String               `tfsdk:"created_at"`
	DeletedAt                 types.String               `tfsdk:"deleted_at"`
	UpdatedAt                 types.String               `tfsdk:"updated_at"`
}
