// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type MagicVault struct {
	AllowUnauthedViews types.Bool  `tfsdk:"allow_unauthed_views"`
	AllowedViews       types.Int64 `tfsdk:"allowed_views"`
}
