// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type MSTeamsChannel struct {
	ChannelName         types.String `tfsdk:"channel_name"`
	ExternalDirectoryID types.String `tfsdk:"external_directory_id"`
}
