// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5473fb865719

package types

type MultiAppSetup struct {
	AppEntitlementDetails map[string]EntitlementToDetails `tfsdk:"app_entitlement_details"`
	AppEntitlements       map[string]MultiAppEntitlement  `tfsdk:"app_entitlements"`
}
