// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type PolicyStep struct {
	Accept    *Accept      `tfsdk:"accept"`
	Approval  *Approval    `tfsdk:"approval" tfPlanOnly:"true"`
	Form      types.String `tfsdk:"form"`
	Provision *Provision   `tfsdk:"provision"`
	Reject    *Reject      `tfsdk:"reject"`
	Wait      *Wait        `tfsdk:"wait"`
}
