// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type PolicyInstance struct {
	History            []PolicyStepInstance `tfsdk:"history"`
	Next               []PolicyStep         `tfsdk:"next"`
	Policy             *Policy              `tfsdk:"policy"`
	PolicyStepInstance *PolicyStepInstance  `tfsdk:"policy_step_instance"`
}
