// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type RequestSchemaForm struct {
	Description        types.String        `tfsdk:"description"`
	FieldGroups        []FormFieldGroup    `tfsdk:"field_groups"`
	FieldRelationships []FieldRelationship `tfsdk:"field_relationships"`
	Fields             []FormField         `tfsdk:"fields"`
	Name               types.String        `tfsdk:"name"`
}
