// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type StoreCredential struct {
	AppIDCel          types.String `tfsdk:"app_id_cel"`
	AuthType          types.String `tfsdk:"auth_type"`
	CredentialCel     types.String `tfsdk:"credential_cel"`
	Expiry            types.String `tfsdk:"expiry"`
	LabelCel          types.String `tfsdk:"label_cel"`
	MaxViews          types.Int64  `tfsdk:"max_views"`
	RecipientCel      types.String `tfsdk:"recipient_cel"`
	RecipientEmailCel types.String `tfsdk:"recipient_email_cel"`
	Ttl               types.String `tfsdk:"ttl"`
	VaultType         types.String `tfsdk:"vault_type"`
}
