// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 408eb9ccde1d

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type WaitForDuration struct {
	Duration types.String `tfsdk:"duration"`
}
