// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// The FacetRange message.
type FacetRange struct {
	// The count of items in the range.
	Count *int64 `integer:"string" json:"count,omitempty"`
	// The display name of the range.
	DisplayName *string `json:"displayName,omitempty"`
	// The starting value of the range.
	From *int64 `integer:"string" json:"from,omitempty"`
	// The icon of the range.
	IconURL *string `json:"iconUrl,omitempty"`
	// The ending value of the range.
	To *int64 `integer:"string" json:"to,omitempty"`
}

func (o *FacetRange) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *FacetRange) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *FacetRange) GetFrom() *int64 {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *FacetRange) GetIconURL() *string {
	if o == nil {
		return nil
	}
	return o.IconURL
}

func (o *FacetRange) GetTo() *int64 {
	if o == nil {
		return nil
	}
	return o.To
}
