// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// The FunctionsServiceCreateFunctionResponse message.
type FunctionsServiceCreateFunctionResponse struct {
	// FunctionCommit represents a single commit in a function's history
	FunctionCommit *FunctionCommit `json:"commit,omitempty"`
	// Function represents a customer-provided code extension in the API
	Function *Function `json:"function,omitempty"`
}

func (o *FunctionsServiceCreateFunctionResponse) GetFunctionCommit() *FunctionCommit {
	if o == nil {
		return nil
	}
	return o.FunctionCommit
}

func (o *FunctionsServiceCreateFunctionResponse) GetFunction() *Function {
	if o == nil {
		return nil
	}
	return o.Function
}
