// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RemoveAppOwnerResponse - Empty response with a status code indicating success.
type RemoveAppOwnerResponse struct {
}
