// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type C1APIRequestcatalogV1RequestCatalogManagementServiceGetBundleAutomationRequest struct {
	RequestCatalogID string `pathParam:"style=simple,explode=false,name=request_catalog_id"`
}

func (o *C1APIRequestcatalogV1RequestCatalogManagementServiceGetBundleAutomationRequest) GetRequestCatalogID() string {
	if o == nil {
		return ""
	}
	return o.RequestCatalogID
}

type C1APIRequestcatalogV1RequestCatalogManagementServiceGetBundleAutomationResponse struct {
	// Successful response
	BundleAutomation *shared.BundleAutomation
	ContentType      string
	StatusCode       int
	RawResponse      *http.Response
}

func (o *C1APIRequestcatalogV1RequestCatalogManagementServiceGetBundleAutomationResponse) GetBundleAutomation() *shared.BundleAutomation {
	if o == nil {
		return nil
	}
	return o.BundleAutomation
}

func (o *C1APIRequestcatalogV1RequestCatalogManagementServiceGetBundleAutomationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *C1APIRequestcatalogV1RequestCatalogManagementServiceGetBundleAutomationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *C1APIRequestcatalogV1RequestCatalogManagementServiceGetBundleAutomationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
