// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"conductorone/internal/sdk/pkg/models/shared"
	"net/http"
)

type C1APIAppV1AppOwnersListRequest struct {
	AppID     string   `pathParam:"style=simple,explode=false,name=app_id"`
	PageSize  *float64 `queryParam:"style=form,explode=true,name=page_size"`
	PageToken *string  `queryParam:"style=form,explode=true,name=page_token"`
}

type C1APIAppV1AppOwnersListResponse struct {
	ContentType string
	// Successful response
	ListAppOwnersResponse *shared.ListAppOwnersResponse
	StatusCode            int
	RawResponse           *http.Response
}
