// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/conductorone/terraform-provider-conductorone/internal/sdk/pkg/models/shared"
	"net/http"
)

type C1APIAuthV1AuthIntrospectResponse struct {
	ContentType string
	// Successful response
	IntrospectResponse *shared.IntrospectResponse
	StatusCode         int
	RawResponse        *http.Response
}
