name: CI

on:
  pull_request:
    branches: [ terraform_v2, main ]
    paths-ignore:
      - 'README.md'
      - 'website/*'
  push:
    branches: [ terraform_v2, main ]
    paths-ignore:
      - 'README.md'
      - 'website/*'

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Run linters
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: latest

      - name: Generate
        run: make generate

      - name: Confirm no diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo "*** Unexpected differences after code generation. Run 'make generate' and commit."; exit 1)

      - name: Build
        run: make build

  test:
    name: 'Acc. Tests (OS: ${{ matrix.os }} / TF: ${{ matrix.terraform }})'
    needs: build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        terraform:
          - '0.12.*'
          - '0.13.*'
          - '0.14.*'
          - '0.15.*'
          - '1.0.*'
          - '1.1.*'
          - '1.2.*'
          - '1.3.*'
          - '1.4.*'
          - '1.5.*'

    steps:

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'

      - name: Setup Terraform ${{ matrix.terraform }}
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Run acceptance test
        run: make testacc
        env:
          CONDUCTORONE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CONDUCTORONE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CONDUCTORONE_SERVER_URL: ${{ secrets.SERVER_URL }}
